$ Spice netlist generated by v2lvs
$ v2020.1_25.14    Mon Feb 3 16:40:08 PST 2020
*.BUSDELIMITER [ 

.SUBCKT datapath__0_27 p_0[23] p_0[22] p_0[21] p_0[20] p_0[19] p_0[18] p_0[17] 
+ p_0[16] p_0[15] p_0[14] p_0[13] p_0[12] p_0[11] p_0[10] p_0[9] p_0[8] p_0[7] 
+ p_0[6] p_0[5] p_0[4] p_0[3] p_0[2] p_0[1] p_0[0] outToAdd[23] outToAdd[22] 
+ outToAdd[21] outToAdd[20] outToAdd[19] outToAdd[18] outToAdd[17] outToAdd[16] 
+ outToAdd[15] outToAdd[14] outToAdd[13] outToAdd[12] outToAdd[11] outToAdd[10] 
+ outToAdd[9] outToAdd[8] outToAdd[7] outToAdd[6] outToAdd[5] outToAdd[4] 
+ outToAdd[3] outToAdd[2] outToAdd[1] outToAdd[0] 
Xi_46 INV_X1 $PINS ZN=n_23 A=outToAdd[19] 
Xi_45 INV_X1 $PINS ZN=n_22 A=outToAdd[15] 
Xi_44 INV_X1 $PINS ZN=n_21 A=outToAdd[11] 
Xi_43 OR3_X1 $PINS ZN=n_20 A1=outToAdd[2] A2=outToAdd[1] A3=outToAdd[0] 
Xi_42 OR2_X1 $PINS ZN=n_19 A1=n_20 A2=outToAdd[3] 
Xi_41 OR2_X1 $PINS ZN=n_18 A1=n_19 A2=outToAdd[4] 
Xi_40 OR3_X1 $PINS ZN=n_17 A1=n_18 A2=outToAdd[5] A3=outToAdd[6] 
Xi_39 OR2_X1 $PINS ZN=n_16 A1=n_17 A2=outToAdd[7] 
Xi_38 OR3_X1 $PINS ZN=n_15 A1=n_16 A2=outToAdd[8] A3=outToAdd[9] 
Xi_37 NOR2_X1 $PINS ZN=n_14 A1=n_15 A2=outToAdd[10] 
Xi_36 NAND2_X1 $PINS ZN=n_13 A1=n_14 A2=n_21 
Xi_35 OR2_X1 $PINS ZN=n_12 A1=n_13 A2=outToAdd[12] 
Xi_34 NOR2_X1 $PINS ZN=n_11 A1=n_12 A2=outToAdd[13] 
Xi_33 NOR3_X1 $PINS ZN=n_10 A1=n_12 A2=outToAdd[13] A3=outToAdd[14] 
Xi_32 NAND2_X1 $PINS ZN=n_9 A1=n_10 A2=n_22 
Xi_31 OR2_X1 $PINS ZN=n_8 A1=n_9 A2=outToAdd[16] 
Xi_30 NOR2_X1 $PINS ZN=n_7 A1=n_8 A2=outToAdd[17] 
Xi_29 NOR3_X1 $PINS ZN=n_6 A1=n_8 A2=outToAdd[17] A3=outToAdd[18] 
Xi_28 NAND2_X1 $PINS ZN=n_5 A1=n_6 A2=n_23 
Xi_27 OR2_X1 $PINS ZN=n_4 A1=n_5 A2=outToAdd[20] 
Xi_26 NOR2_X1 $PINS ZN=n_3 A1=n_4 A2=outToAdd[21] 
Xi_25 NOR3_X1 $PINS ZN=p_0[23] A1=n_4 A2=outToAdd[21] A3=outToAdd[22] 
Xi_24 XNOR2_X1 $PINS ZN=p_0[22] A=outToAdd[22] B=n_3 
Xi_23 XOR2_X1 $PINS Z=p_0[21] A=outToAdd[21] B=n_4 
Xi_22 XOR2_X1 $PINS Z=p_0[20] A=outToAdd[20] B=n_5 
Xi_21 XNOR2_X1 $PINS ZN=p_0[19] A=outToAdd[19] B=n_6 
Xi_20 XNOR2_X1 $PINS ZN=p_0[18] A=outToAdd[18] B=n_7 
Xi_19 XOR2_X1 $PINS Z=p_0[17] A=outToAdd[17] B=n_8 
Xi_18 XOR2_X1 $PINS Z=p_0[16] A=outToAdd[16] B=n_9 
Xi_17 XNOR2_X1 $PINS ZN=p_0[15] A=outToAdd[15] B=n_10 
Xi_16 XNOR2_X1 $PINS ZN=p_0[14] A=outToAdd[14] B=n_11 
Xi_15 XOR2_X1 $PINS Z=p_0[13] A=outToAdd[13] B=n_12 
Xi_14 XOR2_X1 $PINS Z=p_0[12] A=outToAdd[12] B=n_13 
Xi_13 XNOR2_X1 $PINS ZN=p_0[11] A=outToAdd[11] B=n_14 
Xi_12 XOR2_X1 $PINS Z=p_0[10] A=outToAdd[10] B=n_15 
Xi_11 OAI21_X1 $PINS ZN=n_2 A=outToAdd[9] B1=n_16 B2=outToAdd[8] 
Xi_10 AND2_X1 $PINS ZN=p_0[9] A1=n_15 A2=n_2 
Xi_9 XOR2_X1 $PINS Z=p_0[8] A=outToAdd[8] B=n_16 
Xi_8 XOR2_X1 $PINS Z=p_0[7] A=outToAdd[7] B=n_17 
Xi_7 OAI21_X1 $PINS ZN=n_1 A=outToAdd[6] B1=n_18 B2=outToAdd[5] 
Xi_6 AND2_X1 $PINS ZN=p_0[6] A1=n_17 A2=n_1 
Xi_5 XOR2_X1 $PINS Z=p_0[5] A=outToAdd[5] B=n_18 
Xi_4 XOR2_X1 $PINS Z=p_0[4] A=outToAdd[4] B=n_19 
Xi_3 XOR2_X1 $PINS Z=p_0[3] A=outToAdd[3] B=n_20 
Xi_2 OAI21_X1 $PINS ZN=n_0 A=outToAdd[2] B1=outToAdd[1] B2=outToAdd[0] 
Xi_1 AND2_X1 $PINS ZN=p_0[2] A1=n_20 A2=n_0 
Xi_0 XOR2_X1 $PINS Z=p_0[1] A=outToAdd[1] B=outToAdd[0] 
.ENDS

.SUBCKT datapath__0_24 p_0[23] p_0[22] p_0[21] p_0[20] p_0[19] p_0[18] p_0[17] 
+ p_0[16] p_0[15] p_0[14] p_0[13] p_0[12] p_0[11] p_0[10] p_0[9] p_0[8] p_0[7] 
+ p_0[6] p_0[5] p_0[4] p_0[3] p_0[2] p_0[1] p_0[0] shiftedToAdd[23] 
+ shiftedToAdd[22] shiftedToAdd[21] shiftedToAdd[20] shiftedToAdd[19] 
+ shiftedToAdd[18] shiftedToAdd[17] shiftedToAdd[16] shiftedToAdd[15] 
+ shiftedToAdd[14] shiftedToAdd[13] shiftedToAdd[12] shiftedToAdd[11] 
+ shiftedToAdd[10] shiftedToAdd[9] shiftedToAdd[8] shiftedToAdd[7] 
+ shiftedToAdd[6] shiftedToAdd[5] shiftedToAdd[4] shiftedToAdd[3] 
+ shiftedToAdd[2] shiftedToAdd[1] shiftedToAdd[0] 
Xi_46 INV_X1 $PINS ZN=n_23 A=shiftedToAdd[15] 
Xi_45 INV_X1 $PINS ZN=n_22 A=shiftedToAdd[11] 
Xi_44 OR3_X1 $PINS ZN=n_21 A1=shiftedToAdd[2] A2=shiftedToAdd[1] 
+ A3=shiftedToAdd[0] 
Xi_43 OR2_X1 $PINS ZN=n_20 A1=n_21 A2=shiftedToAdd[3] 
Xi_42 OR2_X1 $PINS ZN=n_19 A1=n_20 A2=shiftedToAdd[4] 
Xi_41 OR3_X1 $PINS ZN=n_18 A1=n_19 A2=shiftedToAdd[5] A3=shiftedToAdd[6] 
Xi_40 OR2_X1 $PINS ZN=n_17 A1=n_18 A2=shiftedToAdd[7] 
Xi_39 OR3_X1 $PINS ZN=n_16 A1=n_17 A2=shiftedToAdd[8] A3=shiftedToAdd[9] 
Xi_38 NOR2_X1 $PINS ZN=n_15 A1=n_16 A2=shiftedToAdd[10] 
Xi_37 NAND2_X1 $PINS ZN=n_14 A1=n_15 A2=n_22 
Xi_36 OR2_X1 $PINS ZN=n_13 A1=n_14 A2=shiftedToAdd[12] 
Xi_35 NOR2_X1 $PINS ZN=n_12 A1=n_13 A2=shiftedToAdd[13] 
Xi_34 NOR3_X1 $PINS ZN=n_11 A1=n_13 A2=shiftedToAdd[13] A3=shiftedToAdd[14] 
Xi_33 NAND2_X1 $PINS ZN=n_10 A1=n_11 A2=n_23 
Xi_32 OR2_X1 $PINS ZN=n_9 A1=n_10 A2=shiftedToAdd[16] 
Xi_31 OR2_X1 $PINS ZN=n_8 A1=n_9 A2=shiftedToAdd[17] 
Xi_30 OR3_X1 $PINS ZN=n_7 A1=n_8 A2=shiftedToAdd[18] A3=shiftedToAdd[19] 
Xi_29 NOR2_X1 $PINS ZN=n_6 A1=n_7 A2=shiftedToAdd[20] 
Xi_28 NOR3_X1 $PINS ZN=n_5 A1=n_7 A2=shiftedToAdd[20] A3=shiftedToAdd[21] 
Xi_27 NOR4_X1 $PINS ZN=n_4 A1=n_7 A2=shiftedToAdd[20] A3=shiftedToAdd[21] 
+ A4=shiftedToAdd[22] 
Xi_26 XNOR2_X1 $PINS ZN=p_0[23] A=shiftedToAdd[23] B=n_4 
Xi_25 XNOR2_X1 $PINS ZN=p_0[22] A=shiftedToAdd[22] B=n_5 
Xi_24 XNOR2_X1 $PINS ZN=p_0[21] A=shiftedToAdd[21] B=n_6 
Xi_23 XOR2_X1 $PINS Z=p_0[20] A=shiftedToAdd[20] B=n_7 
Xi_22 OAI21_X1 $PINS ZN=n_3 A=shiftedToAdd[19] B1=n_8 B2=shiftedToAdd[18] 
Xi_21 AND2_X1 $PINS ZN=p_0[19] A1=n_7 A2=n_3 
Xi_20 XOR2_X1 $PINS Z=p_0[18] A=shiftedToAdd[18] B=n_8 
Xi_19 XOR2_X1 $PINS Z=p_0[17] A=shiftedToAdd[17] B=n_9 
Xi_18 XOR2_X1 $PINS Z=p_0[16] A=shiftedToAdd[16] B=n_10 
Xi_17 XNOR2_X1 $PINS ZN=p_0[15] A=shiftedToAdd[15] B=n_11 
Xi_16 XNOR2_X1 $PINS ZN=p_0[14] A=shiftedToAdd[14] B=n_12 
Xi_15 XOR2_X1 $PINS Z=p_0[13] A=shiftedToAdd[13] B=n_13 
Xi_14 XOR2_X1 $PINS Z=p_0[12] A=shiftedToAdd[12] B=n_14 
Xi_13 XNOR2_X1 $PINS ZN=p_0[11] A=shiftedToAdd[11] B=n_15 
Xi_12 XOR2_X1 $PINS Z=p_0[10] A=shiftedToAdd[10] B=n_16 
Xi_11 OAI21_X1 $PINS ZN=n_2 A=shiftedToAdd[9] B1=n_17 B2=shiftedToAdd[8] 
Xi_10 AND2_X1 $PINS ZN=p_0[9] A1=n_16 A2=n_2 
Xi_9 XOR2_X1 $PINS Z=p_0[8] A=shiftedToAdd[8] B=n_17 
Xi_8 XOR2_X1 $PINS Z=p_0[7] A=shiftedToAdd[7] B=n_18 
Xi_7 OAI21_X1 $PINS ZN=n_1 A=shiftedToAdd[6] B1=n_19 B2=shiftedToAdd[5] 
Xi_6 AND2_X1 $PINS ZN=p_0[6] A1=n_18 A2=n_1 
Xi_5 XOR2_X1 $PINS Z=p_0[5] A=shiftedToAdd[5] B=n_19 
Xi_4 XOR2_X1 $PINS Z=p_0[4] A=shiftedToAdd[4] B=n_20 
Xi_3 XOR2_X1 $PINS Z=p_0[3] A=shiftedToAdd[3] B=n_21 
Xi_2 OAI21_X1 $PINS ZN=n_0 A=shiftedToAdd[2] B1=shiftedToAdd[1] 
+ B2=shiftedToAdd[0] 
Xi_1 AND2_X1 $PINS ZN=p_0[2] A1=n_21 A2=n_0 
Xi_0 XOR2_X1 $PINS Z=p_0[1] A=shiftedToAdd[1] B=shiftedToAdd[0] 
.ENDS

.SUBCKT datapath__0_11 p_0[23] p_0[22] p_0[21] p_0[20] p_0[19] p_0[18] p_0[17] 
+ p_0[16] p_0[15] p_0[14] p_0[13] p_0[12] p_0[11] p_0[10] p_0[9] p_0[8] p_0[7] 
+ p_0[6] p_0[5] p_0[4] p_0[3] p_0[2] p_0[1] p_0[0] unNormalizedSum[23] 
+ unNormalizedSum[22] unNormalizedSum[21] unNormalizedSum[20] 
+ unNormalizedSum[19] unNormalizedSum[18] unNormalizedSum[17] 
+ unNormalizedSum[16] unNormalizedSum[15] unNormalizedSum[14] 
+ unNormalizedSum[13] unNormalizedSum[12] unNormalizedSum[11] 
+ unNormalizedSum[10] unNormalizedSum[9] unNormalizedSum[8] unNormalizedSum[7] 
+ unNormalizedSum[6] unNormalizedSum[5] unNormalizedSum[4] unNormalizedSum[3] 
+ unNormalizedSum[2] unNormalizedSum[1] unNormalizedSum[0] 
Xi_46 INV_X1 $PINS ZN=n_23 A=unNormalizedSum[15] 
Xi_45 INV_X1 $PINS ZN=n_22 A=unNormalizedSum[11] 
Xi_44 OR3_X1 $PINS ZN=n_21 A1=unNormalizedSum[2] A2=unNormalizedSum[1] 
+ A3=unNormalizedSum[0] 
Xi_43 OR2_X1 $PINS ZN=n_20 A1=n_21 A2=unNormalizedSum[3] 
Xi_42 OR2_X1 $PINS ZN=n_19 A1=n_20 A2=unNormalizedSum[4] 
Xi_41 OR3_X1 $PINS ZN=n_18 A1=n_19 A2=unNormalizedSum[5] A3=unNormalizedSum[6] 
Xi_40 OR2_X1 $PINS ZN=n_17 A1=n_18 A2=unNormalizedSum[7] 
Xi_39 OR3_X1 $PINS ZN=n_16 A1=n_17 A2=unNormalizedSum[8] A3=unNormalizedSum[9] 
Xi_38 NOR2_X1 $PINS ZN=n_15 A1=n_16 A2=unNormalizedSum[10] 
Xi_37 NAND2_X1 $PINS ZN=n_14 A1=n_15 A2=n_22 
Xi_36 OR2_X1 $PINS ZN=n_13 A1=n_14 A2=unNormalizedSum[12] 
Xi_35 NOR2_X1 $PINS ZN=n_12 A1=n_13 A2=unNormalizedSum[13] 
Xi_34 NOR3_X1 $PINS ZN=n_11 A1=n_13 A2=unNormalizedSum[13] 
+ A3=unNormalizedSum[14] 
Xi_33 NAND2_X1 $PINS ZN=n_10 A1=n_11 A2=n_23 
Xi_32 OR2_X1 $PINS ZN=n_9 A1=n_10 A2=unNormalizedSum[16] 
Xi_31 OR2_X1 $PINS ZN=n_8 A1=n_9 A2=unNormalizedSum[17] 
Xi_30 OR3_X1 $PINS ZN=n_7 A1=n_8 A2=unNormalizedSum[18] A3=unNormalizedSum[19] 
Xi_29 NOR2_X1 $PINS ZN=n_6 A1=n_7 A2=unNormalizedSum[20] 
Xi_28 NOR3_X1 $PINS ZN=n_5 A1=n_7 A2=unNormalizedSum[20] A3=unNormalizedSum[21] 
Xi_27 NOR4_X1 $PINS ZN=n_4 A1=n_7 A2=unNormalizedSum[20] A3=unNormalizedSum[21] 
+ A4=unNormalizedSum[22] 
Xi_26 XNOR2_X1 $PINS ZN=p_0[23] A=unNormalizedSum[23] B=n_4 
Xi_25 XNOR2_X1 $PINS ZN=p_0[22] A=unNormalizedSum[22] B=n_5 
Xi_24 XNOR2_X1 $PINS ZN=p_0[21] A=unNormalizedSum[21] B=n_6 
Xi_23 XOR2_X1 $PINS Z=p_0[20] A=unNormalizedSum[20] B=n_7 
Xi_22 OAI21_X1 $PINS ZN=n_3 A=unNormalizedSum[19] B1=n_8 B2=unNormalizedSum[18] 
Xi_21 AND2_X1 $PINS ZN=p_0[19] A1=n_7 A2=n_3 
Xi_20 XOR2_X1 $PINS Z=p_0[18] A=unNormalizedSum[18] B=n_8 
Xi_19 XOR2_X1 $PINS Z=p_0[17] A=unNormalizedSum[17] B=n_9 
Xi_18 XOR2_X1 $PINS Z=p_0[16] A=unNormalizedSum[16] B=n_10 
Xi_17 XNOR2_X1 $PINS ZN=p_0[15] A=unNormalizedSum[15] B=n_11 
Xi_16 XNOR2_X1 $PINS ZN=p_0[14] A=unNormalizedSum[14] B=n_12 
Xi_15 XOR2_X1 $PINS Z=p_0[13] A=unNormalizedSum[13] B=n_13 
Xi_14 XOR2_X1 $PINS Z=p_0[12] A=unNormalizedSum[12] B=n_14 
Xi_13 XNOR2_X1 $PINS ZN=p_0[11] A=unNormalizedSum[11] B=n_15 
Xi_12 XOR2_X1 $PINS Z=p_0[10] A=unNormalizedSum[10] B=n_16 
Xi_11 OAI21_X1 $PINS ZN=n_2 A=unNormalizedSum[9] B1=n_17 B2=unNormalizedSum[8] 
Xi_10 AND2_X1 $PINS ZN=p_0[9] A1=n_16 A2=n_2 
Xi_9 XOR2_X1 $PINS Z=p_0[8] A=unNormalizedSum[8] B=n_17 
Xi_8 XOR2_X1 $PINS Z=p_0[7] A=unNormalizedSum[7] B=n_18 
Xi_7 OAI21_X1 $PINS ZN=n_1 A=unNormalizedSum[6] B1=n_19 B2=unNormalizedSum[5] 
Xi_6 AND2_X1 $PINS ZN=p_0[6] A1=n_18 A2=n_1 
Xi_5 XOR2_X1 $PINS Z=p_0[5] A=unNormalizedSum[5] B=n_19 
Xi_4 XOR2_X1 $PINS Z=p_0[4] A=unNormalizedSum[4] B=n_20 
Xi_3 XOR2_X1 $PINS Z=p_0[3] A=unNormalizedSum[3] B=n_21 
Xi_2 OAI21_X1 $PINS ZN=n_0 A=unNormalizedSum[2] B1=unNormalizedSum[1] 
+ B2=unNormalizedSum[0] 
Xi_1 AND2_X1 $PINS ZN=p_0[2] A1=n_21 A2=n_0 
Xi_0 XOR2_X1 $PINS Z=p_0[1] A=unNormalizedSum[1] B=unNormalizedSum[0] 
.ENDS

.SUBCKT LZeros in[23] in[22] in[21] in[20] in[19] in[18] in[17] in[16] in[15] 
+ in[14] in[13] in[12] in[11] in[10] in[9] in[8] in[7] in[6] in[5] in[4] in[3] 
+ in[2] in[1] in[0] out[4] out[3] out[2] out[1] out[0] 
Xi_0_48 INV_X1 $PINS ZN=n_0_43 A=n_0_27 
Xi_0_47 INV_X1 $PINS ZN=n_0_42 A=in[19] 
Xi_0_46 INV_X1 $PINS ZN=n_0_41 A=in[13] 
Xi_0_45 INV_X1 $PINS ZN=n_0_40 A=in[12] 
Xi_0_44 INV_X1 $PINS ZN=n_0_39 A=in[9] 
Xi_0_43 INV_X1 $PINS ZN=n_0_38 A=in[8] 
Xi_0_42 INV_X1 $PINS ZN=n_0_37 A=in[5] 
Xi_0_41 INV_X1 $PINS ZN=n_0_36 A=in[4] 
Xi_0_40 INV_X1 $PINS ZN=n_0_35 A=in[1] 
Xi_0_39 NOR4_X1 $PINS ZN=n_0_34 A1=in[23] A2=in[22] A3=in[21] A4=in[20] 
Xi_0_38 INV_X1 $PINS ZN=n_0_33 A=n_0_34 
Xi_0_37 NOR4_X1 $PINS ZN=n_0_32 A1=in[19] A2=in[18] A3=in[17] A4=in[16] 
Xi_0_36 NAND2_X1 $PINS ZN=n_0_31 A1=n_0_34 A2=n_0_32 
Xi_0_35 NOR4_X1 $PINS ZN=n_0_30 A1=in[15] A2=in[14] A3=in[13] A4=in[12] 
Xi_0_34 NOR4_X1 $PINS ZN=n_0_29 A1=in[11] A2=in[10] A3=in[9] A4=in[8] 
Xi_0_33 NAND2_X1 $PINS ZN=n_0_28 A1=n_0_30 A2=n_0_29 
Xi_0_32 OR4_X1 $PINS ZN=n_0_27 A1=in[7] A2=in[6] A3=in[5] A4=in[4] 
Xi_0_31 NOR2_X1 $PINS ZN=n_0_26 A1=in[1] A2=in[0] 
Xi_0_30 NOR4_X1 $PINS ZN=n_0_25 A1=in[3] A2=in[2] A3=in[1] A4=in[0] 
Xi_0_29 AOI211_X2 $PINS ZN=out[4] A=n_0_31 B=n_0_28 C1=n_0_43 C2=n_0_25 
Xi_0_28 AOI21_X2 $PINS ZN=out[3] A=n_0_31 B1=n_0_30 B2=n_0_29 
Xi_0_27 OAI21_X1 $PINS ZN=n_0_24 A=n_0_29 B1=n_0_27 B2=n_0_25 
Xi_0_26 NAND2_X1 $PINS ZN=n_0_23 A1=n_0_24 A2=n_0_30 
Xi_0_25 AOI21_X2 $PINS ZN=out[2] A=n_0_33 B1=n_0_23 B2=n_0_32 
Xi_0_24 NOR3_X1 $PINS ZN=n_0_22 A1=in[3] A2=in[2] A3=n_0_26 
Xi_0_23 NOR3_X1 $PINS ZN=n_0_21 A1=in[5] A2=in[4] A3=n_0_22 
Xi_0_22 NOR3_X1 $PINS ZN=n_0_20 A1=in[7] A2=in[6] A3=n_0_21 
Xi_0_21 NOR3_X1 $PINS ZN=n_0_19 A1=in[9] A2=in[8] A3=n_0_20 
Xi_0_20 NOR3_X1 $PINS ZN=n_0_18 A1=in[11] A2=in[10] A3=n_0_19 
Xi_0_19 NOR3_X1 $PINS ZN=n_0_17 A1=in[13] A2=in[12] A3=n_0_18 
Xi_0_18 NOR3_X1 $PINS ZN=n_0_16 A1=in[15] A2=in[14] A3=n_0_17 
Xi_0_17 NOR3_X1 $PINS ZN=n_0_15 A1=in[17] A2=in[16] A3=n_0_16 
Xi_0_16 NOR3_X1 $PINS ZN=n_0_14 A1=in[19] A2=in[18] A3=n_0_15 
Xi_0_15 NOR3_X1 $PINS ZN=n_0_13 A1=in[21] A2=in[20] A3=n_0_14 
Xi_0_14 NOR3_X2 $PINS ZN=out[1] A1=in[23] A2=in[22] A3=n_0_13 
Xi_0_13 AOI21_X1 $PINS ZN=n_0_12 A=in[20] B1=n_0_42 B2=in[18] 
Xi_0_12 NOR2_X1 $PINS ZN=n_0_11 A1=in[21] A2=n_0_12 
Xi_0_11 NOR2_X1 $PINS ZN=n_0_10 A1=in[22] A2=n_0_11 
Xi_0_10 NOR4_X1 $PINS ZN=n_0_9 A1=in[23] A2=in[21] A3=in[19] A4=in[17] 
Xi_0_9 AOI21_X1 $PINS ZN=n_0_8 A=in[2] B1=n_0_35 B2=in[0] 
Xi_0_8 OAI21_X1 $PINS ZN=n_0_7 A=n_0_36 B1=in[3] B2=n_0_8 
Xi_0_7 AOI21_X1 $PINS ZN=n_0_6 A=in[6] B1=n_0_37 B2=n_0_7 
Xi_0_6 OAI21_X1 $PINS ZN=n_0_5 A=n_0_38 B1=in[7] B2=n_0_6 
Xi_0_5 AOI21_X1 $PINS ZN=n_0_4 A=in[10] B1=n_0_39 B2=n_0_5 
Xi_0_4 OAI21_X1 $PINS ZN=n_0_3 A=n_0_40 B1=in[11] B2=n_0_4 
Xi_0_3 AOI21_X1 $PINS ZN=n_0_2 A=in[14] B1=n_0_41 B2=n_0_3 
Xi_0_2 NOR2_X1 $PINS ZN=n_0_1 A1=in[15] A2=n_0_2 
Xi_0_1 OAI21_X1 $PINS ZN=n_0_0 A=n_0_9 B1=n_0_1 B2=in[16] 
Xi_0_0 OAI21_X1 $PINS ZN=out[0] A=n_0_0 B1=n_0_10 B2=in[23] 
.ENDS

.SUBCKT Multiplixer A[7] A[6] A[5] A[4] A[3] A[2] A[1] A[0] B[7] B[6] B[5] B[4] 
+ B[3] B[2] B[1] B[0] Sel Out[7] Out[6] Out[5] Out[4] Out[3] Out[2] Out[1] 
+ Out[0] 
Xi_0_7 MUX2_X1 $PINS Z=Out[7] A=A[7] B=B[7] S=Sel 
Xi_0_6 MUX2_X1 $PINS Z=Out[6] A=A[6] B=B[6] S=Sel 
Xi_0_5 MUX2_X1 $PINS Z=Out[5] A=A[5] B=B[5] S=Sel 
Xi_0_4 MUX2_X1 $PINS Z=Out[4] A=A[4] B=B[4] S=Sel 
Xi_0_3 MUX2_X1 $PINS Z=Out[3] A=A[3] B=B[3] S=Sel 
Xi_0_2 MUX2_X1 $PINS Z=Out[2] A=A[2] B=B[2] S=Sel 
Xi_0_1 MUX2_X1 $PINS Z=Out[1] A=A[1] B=B[1] S=Sel 
Xi_0_0 MUX2_X1 $PINS Z=Out[0] A=A[0] B=B[0] S=Sel 
.ENDS

.SUBCKT HalfAdder x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT HalfAdder__0_38 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT HalfAdder__0_35 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT HalfAdder__0_32 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT CIN sin[3] sin[2] sin[1] sin[0] cin cprev sumout[3] sumout[2] sumout[1] 
+ sumout[0] carryout 
Xi_0_0 OR2_X1 $PINS ZN=carryout A1=cwire3 A2=cin 
XHA3 HalfAdder $PINS cout=cwire3 z=sumout[3] x=cwire2 y=sin[3] 
XHA2 HalfAdder__0_38 $PINS cout=cwire2 z=sumout[2] x=cwire1 y=sin[2] 
XHA1 HalfAdder__0_35 $PINS cout=cwire1 z=sumout[1] x=cwire0 y=sin[1] 
XHA0 HalfAdder__0_32 $PINS cout=cwire0 z=sumout[0] x=cprev y=sin[0] 
.ENDS

.SUBCKT HalfAdder__0_84 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT HalfAdder__0_87 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT HalfAdder__0_90 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT HalfAdder__0_93 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT CIN__0_94 sin[3] sin[2] sin[1] sin[0] cin cprev sumout[3] sumout[2] 
+ sumout[1] sumout[0] carryout 
Xi_0_0 OR2_X1 $PINS ZN=carryout A1=cwire3 A2=cin 
XHA3 HalfAdder__0_84 $PINS cout=cwire3 z=sumout[3] x=cwire2 y=sin[3] 
XHA2 HalfAdder__0_87 $PINS cout=cwire2 z=sumout[2] x=cwire1 y=sin[2] 
XHA1 HalfAdder__0_90 $PINS cout=cwire1 z=sumout[1] x=cwire0 y=sin[1] 
XHA0 HalfAdder__0_93 $PINS cout=cwire0 z=sumout[0] x=cprev y=sin[0] 
.ENDS

.SUBCKT HalfAdder__0_70 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT HalfAdder__0_73 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT HalfAdder__0_76 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT HalfAdder__0_79 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT CIN__0_80 sin[3] sin[2] sin[1] sin[0] cin cprev sumout[3] sumout[2] 
+ sumout[1] sumout[0] carryout 
Xi_0_0 OR2_X1 $PINS ZN=carryout A1=cwire3 A2=cin 
XHA3 HalfAdder__0_70 $PINS cout=cwire3 z=sumout[3] x=cwire2 y=sin[3] 
XHA2 HalfAdder__0_73 $PINS cout=cwire2 z=sumout[2] x=cwire1 y=sin[2] 
XHA1 HalfAdder__0_76 $PINS cout=cwire1 z=sumout[1] x=cwire0 y=sin[1] 
XHA0 HalfAdder__0_79 $PINS cout=cwire0 z=sumout[0] x=cprev y=sin[0] 
.ENDS

.SUBCKT HalfAdder__0_56 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT HalfAdder__0_59 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT HalfAdder__0_62 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT HalfAdder__0_65 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT CIN__0_66 sin[3] sin[2] sin[1] sin[0] cin cprev sumout[3] sumout[2] 
+ sumout[1] sumout[0] carryout 
Xi_0_0 OR2_X1 $PINS ZN=carryout A1=cwire3 A2=cin 
XHA3 HalfAdder__0_56 $PINS cout=cwire3 z=sumout[3] x=cwire2 y=sin[3] 
XHA2 HalfAdder__0_59 $PINS cout=cwire2 z=sumout[2] x=cwire1 y=sin[2] 
XHA1 HalfAdder__0_62 $PINS cout=cwire1 z=sumout[1] x=cwire0 y=sin[1] 
XHA0 HalfAdder__0_65 $PINS cout=cwire0 z=sumout[0] x=cprev y=sin[0] 
.ENDS

.SUBCKT HalfAdder__0_42 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT HalfAdder__0_45 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT HalfAdder__0_48 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT HalfAdder__0_51 x y z cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=x A2=y 
Xi_0_0 XOR2_X1 $PINS Z=z A=x B=y 
.ENDS

.SUBCKT CIN__0_52 sin[3] sin[2] sin[1] sin[0] cin cprev sumout[3] sumout[2] 
+ sumout[1] sumout[0] carryout 
Xi_0_0 OR2_X1 $PINS ZN=carryout A1=cwire3 A2=cin 
XHA3 HalfAdder__0_42 $PINS cout=cwire3 z=sumout[3] x=cwire2 y=sin[3] 
XHA2 HalfAdder__0_45 $PINS cout=cwire2 z=sumout[2] x=cwire1 y=sin[2] 
XHA1 HalfAdder__0_48 $PINS cout=cwire1 z=sumout[1] x=cwire0 y=sin[1] 
XHA0 HalfAdder__0_51 $PINS cout=cwire0 z=sumout[0] x=cprev y=sin[0] 
.ENDS

.SUBCKT FA in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_106 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_102 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_98 in1 in2 cin sum cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=in2 A2=in1 
Xi_0_0 XOR2_X1 $PINS Z=sum A=in1 B=in2 
.ENDS

.SUBCKT RCA4bit in1[3] in1[2] in1[1] in1[0] in2[3] in2[2] in2[1] in2[0] cin 
+ sum[3] sum[2] sum[1] sum[0] cout 
Xgenblk1_3_full_adder_inst FA $PINS cout=cout sum=sum[3] cin=carries[3] 
+ in1=in1[3] in2=in2[3] 
Xgenblk1_2_full_adder_inst FA__0_106 $PINS cout=carries[3] sum=sum[2] 
+ cin=carries[2] in1=in1[2] in2=in2[2] 
Xgenblk1_1_full_adder_inst FA__0_102 $PINS cout=carries[2] sum=sum[1] 
+ cin=carries[1] in1=in1[1] in2=in2[1] 
Xgenblk1_0_full_adder_inst FA__0_98 $PINS cout=carries[1] sum=sum[0] in1=in1[0] 
+ in2=in2[0] 
.ENDS

.SUBCKT FA__0_178 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_182 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_186 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_190 in1 in2 cin sum cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=in2 A2=in1 
Xi_0_0 XOR2_X1 $PINS Z=sum A=in1 B=in2 
.ENDS

.SUBCKT RCA4bit__0_191 in1[3] in1[2] in1[1] in1[0] in2[3] in2[2] in2[1] in2[0] 
+ cin sum[3] sum[2] sum[1] sum[0] cout 
Xgenblk1_3_full_adder_inst FA__0_178 $PINS cout=cout sum=sum[3] cin=carries[3] 
+ in1=in1[3] in2=in2[3] 
Xgenblk1_2_full_adder_inst FA__0_182 $PINS cout=carries[3] sum=sum[2] 
+ cin=carries[2] in1=in1[2] in2=in2[2] 
Xgenblk1_1_full_adder_inst FA__0_186 $PINS cout=carries[2] sum=sum[1] 
+ cin=carries[1] in1=in1[1] in2=in2[1] 
Xgenblk1_0_full_adder_inst FA__0_190 $PINS cout=carries[1] sum=sum[0] 
+ in1=in1[0] in2=in2[0] 
.ENDS

.SUBCKT FA__0_161 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_165 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_169 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_173 in1 in2 cin sum cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=in2 A2=in1 
Xi_0_0 XOR2_X1 $PINS Z=sum A=in1 B=in2 
.ENDS

.SUBCKT RCA4bit__0_174 in1[3] in1[2] in1[1] in1[0] in2[3] in2[2] in2[1] in2[0] 
+ cin sum[3] sum[2] sum[1] sum[0] cout 
Xgenblk1_3_full_adder_inst FA__0_161 $PINS cout=cout sum=sum[3] cin=carries[3] 
+ in1=in1[3] in2=in2[3] 
Xgenblk1_2_full_adder_inst FA__0_165 $PINS cout=carries[3] sum=sum[2] 
+ cin=carries[2] in1=in1[2] in2=in2[2] 
Xgenblk1_1_full_adder_inst FA__0_169 $PINS cout=carries[2] sum=sum[1] 
+ cin=carries[1] in1=in1[1] in2=in2[1] 
Xgenblk1_0_full_adder_inst FA__0_173 $PINS cout=carries[1] sum=sum[0] 
+ in1=in1[0] in2=in2[0] 
.ENDS

.SUBCKT FA__0_144 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_148 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_152 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_156 in1 in2 cin sum cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=in2 A2=in1 
Xi_0_0 XOR2_X1 $PINS Z=sum A=in1 B=in2 
.ENDS

.SUBCKT RCA4bit__0_157 in1[3] in1[2] in1[1] in1[0] in2[3] in2[2] in2[1] in2[0] 
+ cin sum[3] sum[2] sum[1] sum[0] cout 
Xgenblk1_3_full_adder_inst FA__0_144 $PINS cout=cout sum=sum[3] cin=carries[3] 
+ in1=in1[3] in2=in2[3] 
Xgenblk1_2_full_adder_inst FA__0_148 $PINS cout=carries[3] sum=sum[2] 
+ cin=carries[2] in1=in1[2] in2=in2[2] 
Xgenblk1_1_full_adder_inst FA__0_152 $PINS cout=carries[2] sum=sum[1] 
+ cin=carries[1] in1=in1[1] in2=in2[1] 
Xgenblk1_0_full_adder_inst FA__0_156 $PINS cout=carries[1] sum=sum[0] 
+ in1=in1[0] in2=in2[0] 
.ENDS

.SUBCKT FA__0_127 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_131 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_135 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_139 in1 in2 cin sum cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=in2 A2=in1 
Xi_0_0 XOR2_X1 $PINS Z=sum A=in1 B=in2 
.ENDS

.SUBCKT RCA4bit__0_140 in1[3] in1[2] in1[1] in1[0] in2[3] in2[2] in2[1] in2[0] 
+ cin sum[3] sum[2] sum[1] sum[0] cout 
Xgenblk1_3_full_adder_inst FA__0_127 $PINS cout=cout sum=sum[3] cin=carries[3] 
+ in1=in1[3] in2=in2[3] 
Xgenblk1_2_full_adder_inst FA__0_131 $PINS cout=carries[3] sum=sum[2] 
+ cin=carries[2] in1=in1[2] in2=in2[2] 
Xgenblk1_1_full_adder_inst FA__0_135 $PINS cout=carries[2] sum=sum[1] 
+ cin=carries[1] in1=in1[1] in2=in2[1] 
Xgenblk1_0_full_adder_inst FA__0_139 $PINS cout=carries[1] sum=sum[0] 
+ in1=in1[0] in2=in2[0] 
.ENDS

.SUBCKT FA__0_110 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_114 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_118 in1 in2 cin sum cout 
Xi_0_3 INV_X1 $PINS ZN=cout A=n_0_0 
Xi_0_2 AOI22_X1 $PINS ZN=n_0_0 A1=w0 A2=cin B1=in1 B2=in2 
Xi_0_1 XOR2_X1 $PINS Z=sum A=cin B=w0 
Xi_0_0 XOR2_X1 $PINS Z=w0 A=in1 B=in2 
.ENDS

.SUBCKT FA__0_122 in1 in2 cin sum cout 
Xi_0_1 AND2_X1 $PINS ZN=cout A1=in2 A2=in1 
Xi_0_0 XOR2_X1 $PINS Z=sum A=in1 B=in2 
.ENDS

.SUBCKT RCA4bit__0_123 in1[3] in1[2] in1[1] in1[0] in2[3] in2[2] in2[1] in2[0] 
+ cin sum[3] sum[2] sum[1] sum[0] cout 
Xgenblk1_3_full_adder_inst FA__0_110 $PINS cout=cout sum=sum[3] cin=carries[3] 
+ in1=in1[3] in2=in2[3] 
Xgenblk1_2_full_adder_inst FA__0_114 $PINS cout=carries[3] sum=sum[2] 
+ cin=carries[2] in1=in1[2] in2=in2[2] 
Xgenblk1_1_full_adder_inst FA__0_118 $PINS cout=carries[2] sum=sum[1] 
+ cin=carries[1] in1=in1[1] in2=in2[1] 
Xgenblk1_0_full_adder_inst FA__0_122 $PINS cout=carries[1] sum=sum[0] 
+ in1=in1[0] in2=in2[0] 
.ENDS

.SUBCKT CIA_24bit in1[23] in1[22] in1[21] in1[20] in1[19] in1[18] in1[17] 
+ in1[16] in1[15] in1[14] in1[13] in1[12] in1[11] in1[10] in1[9] in1[8] in1[7] 
+ in1[6] in1[5] in1[4] in1[3] in1[2] in1[1] in1[0] in2[23] in2[22] in2[21] 
+ in2[20] in2[19] in2[18] in2[17] in2[16] in2[15] in2[14] in2[13] in2[12] 
+ in2[11] in2[10] in2[9] in2[8] in2[7] in2[6] in2[5] in2[4] in2[3] in2[2] 
+ in2[1] in2[0] sum[23] sum[22] sum[21] sum[20] sum[19] sum[18] sum[17] sum[16] 
+ sum[15] sum[14] sum[13] sum[12] sum[11] sum[10] sum[9] sum[8] sum[7] sum[6] 
+ sum[5] sum[4] sum[3] sum[2] sum[1] sum[0] carry 
XCIN4_5 CIN $PINS carryout=carry sumout[3]=sum[23] sumout[2]=sum[22] 
+ sumout[1]=sum[21] sumout[0]=sum[20] cin=carrywire[5] cprev=n_0 
+ sin[3]=sumwire5[3] sin[2]=sumwire5[2] sin[1]=sumwire5[1] sin[0]=sumwire5[0] 
XCIN0_1 CIN__0_94 $PINS carryout=n_3 sumout[3]=sum[7] sumout[2]=sum[6] 
+ sumout[1]=sum[5] sumout[0]=sum[4] cin=carrywire[1] cprev=carrywire[0] 
+ sin[3]=sumwire1[3] sin[2]=sumwire1[2] sin[1]=sumwire1[1] sin[0]=sumwire1[0] 
XCIN1_2 CIN__0_80 $PINS carryout=n_2 sumout[3]=sum[11] sumout[2]=sum[10] 
+ sumout[1]=sum[9] sumout[0]=sum[8] cin=carrywire[2] cprev=n_3 sin[3]=sumwire2[3] 
+ sin[2]=sumwire2[2] sin[1]=sumwire2[1] sin[0]=sumwire2[0] 
XCIN2_3 CIN__0_66 $PINS carryout=n_1 sumout[3]=sum[15] sumout[2]=sum[14] 
+ sumout[1]=sum[13] sumout[0]=sum[12] cin=carrywire[3] cprev=n_2 
+ sin[3]=sumwire3[3] sin[2]=sumwire3[2] sin[1]=sumwire3[1] sin[0]=sumwire3[0] 
XCIN3_4 CIN__0_52 $PINS carryout=n_0 sumout[3]=sum[19] sumout[2]=sum[18] 
+ sumout[1]=sum[17] sumout[0]=sum[16] cin=carrywire[4] cprev=n_1 
+ sin[3]=sumwire4[3] sin[2]=sumwire4[2] sin[1]=sumwire4[1] sin[0]=sumwire4[0] 
XRCA0 RCA4bit $PINS cout=carrywire[0] sum[3]=sum[3] sum[2]=sum[2] sum[1]=sum[1] 
+ sum[0]=sum[0] in1[3]=in1[3] in1[2]=in1[2] in1[1]=in1[1] in1[0]=in1[0] 
+ in2[3]=in2[3] in2[2]=in2[2] in2[1]=in2[1] in2[0]=in2[0] 
XRCA1 RCA4bit__0_191 $PINS cout=carrywire[1] sum[3]=sumwire1[3] 
+ sum[2]=sumwire1[2] sum[1]=sumwire1[1] sum[0]=sumwire1[0] in1[3]=in1[7] 
+ in1[2]=in1[6] in1[1]=in1[5] in1[0]=in1[4] in2[3]=in2[7] in2[2]=in2[6] 
+ in2[1]=in2[5] in2[0]=in2[4] 
XRCA2 RCA4bit__0_174 $PINS cout=carrywire[2] sum[3]=sumwire2[3] 
+ sum[2]=sumwire2[2] sum[1]=sumwire2[1] sum[0]=sumwire2[0] in1[3]=in1[11] 
+ in1[2]=in1[10] in1[1]=in1[9] in1[0]=in1[8] in2[3]=in2[11] in2[2]=in2[10] 
+ in2[1]=in2[9] in2[0]=in2[8] 
XRCA3 RCA4bit__0_157 $PINS cout=carrywire[3] sum[3]=sumwire3[3] 
+ sum[2]=sumwire3[2] sum[1]=sumwire3[1] sum[0]=sumwire3[0] in1[3]=in1[15] 
+ in1[2]=in1[14] in1[1]=in1[13] in1[0]=in1[12] in2[3]=in2[15] in2[2]=in2[14] 
+ in2[1]=in2[13] in2[0]=in2[12] 
XRCA4 RCA4bit__0_140 $PINS cout=carrywire[4] sum[3]=sumwire4[3] 
+ sum[2]=sumwire4[2] sum[1]=sumwire4[1] sum[0]=sumwire4[0] in1[3]=in1[19] 
+ in1[2]=in1[18] in1[1]=in1[17] in1[0]=in1[16] in2[3]=in2[19] in2[2]=in2[18] 
+ in2[1]=in2[17] in2[0]=in2[16] 
XRCA5 RCA4bit__0_123 $PINS cout=carrywire[5] sum[3]=sumwire5[3] 
+ sum[2]=sumwire5[2] sum[1]=sumwire5[1] sum[0]=sumwire5[0] in1[3]=in1[23] 
+ in1[2]=in1[22] in1[1]=in1[21] in1[0]=in1[20] in2[3]=in2[23] in2[2]=in2[22] 
+ in2[1]=in2[21] in2[0]=in2[20] 
.ENDS

.SUBCKT Multiplixer__parameterized0 A[24] A[23] A[22] A[21] A[20] A[19] A[18] 
+ A[17] A[16] A[15] A[14] A[13] A[12] A[11] A[10] A[9] A[8] A[7] A[6] A[5] A[4] 
+ A[3] A[2] A[1] A[0] B[24] B[23] B[22] B[21] B[20] B[19] B[18] B[17] B[16] 
+ B[15] B[14] B[13] B[12] B[11] B[10] B[9] B[8] B[7] B[6] B[5] B[4] B[3] B[2] 
+ B[1] B[0] Sel Out[24] Out[23] Out[22] Out[21] Out[20] Out[19] Out[18] Out[17] 
+ Out[16] Out[15] Out[14] Out[13] Out[12] Out[11] Out[10] Out[9] Out[8] Out[7] 
+ Out[6] Out[5] Out[4] Out[3] Out[2] Out[1] Out[0] 
Xi_0_23 MUX2_X1 $PINS Z=Out[24] A=A[24] B=B[24] S=hfn_ipo_n1 
Xi_0_22 MUX2_X1 $PINS Z=Out[22] A=A[22] B=B[22] S=hfn_ipo_n1 
Xi_0_21 MUX2_X1 $PINS Z=Out[21] A=A[21] B=B[21] S=hfn_ipo_n1 
Xi_0_20 MUX2_X1 $PINS Z=Out[20] A=A[20] B=B[20] S=hfn_ipo_n1 
Xi_0_19 MUX2_X1 $PINS Z=Out[19] A=A[19] B=B[19] S=hfn_ipo_n1 
Xi_0_18 MUX2_X1 $PINS Z=Out[18] A=A[18] B=B[18] S=hfn_ipo_n1 
Xi_0_17 MUX2_X1 $PINS Z=Out[17] A=A[17] B=B[17] S=hfn_ipo_n1 
Xi_0_16 MUX2_X1 $PINS Z=Out[16] A=A[16] B=B[16] S=hfn_ipo_n1 
Xi_0_15 MUX2_X1 $PINS Z=Out[15] A=A[15] B=B[15] S=hfn_ipo_n1 
Xi_0_14 MUX2_X1 $PINS Z=Out[14] A=A[14] B=B[14] S=hfn_ipo_n1 
Xi_0_13 MUX2_X1 $PINS Z=Out[13] A=A[13] B=B[13] S=hfn_ipo_n1 
Xi_0_12 MUX2_X1 $PINS Z=Out[12] A=A[12] B=B[12] S=hfn_ipo_n1 
Xi_0_11 MUX2_X1 $PINS Z=Out[11] A=A[11] B=B[11] S=hfn_ipo_n1 
Xi_0_10 MUX2_X1 $PINS Z=Out[10] A=A[10] B=B[10] S=hfn_ipo_n1 
Xi_0_9 MUX2_X1 $PINS Z=Out[9] A=A[9] B=B[9] S=hfn_ipo_n1 
Xi_0_8 MUX2_X1 $PINS Z=Out[8] A=A[8] B=B[8] S=hfn_ipo_n1 
Xi_0_7 MUX2_X1 $PINS Z=Out[7] A=A[7] B=B[7] S=hfn_ipo_n1 
Xi_0_6 MUX2_X1 $PINS Z=Out[6] A=A[6] B=B[6] S=hfn_ipo_n1 
Xi_0_5 MUX2_X1 $PINS Z=Out[5] A=A[5] B=B[5] S=hfn_ipo_n1 
Xi_0_4 MUX2_X1 $PINS Z=Out[4] A=A[4] B=B[4] S=hfn_ipo_n1 
Xi_0_3 MUX2_X1 $PINS Z=Out[3] A=A[3] B=B[3] S=hfn_ipo_n1 
Xi_0_2 MUX2_X1 $PINS Z=Out[2] A=A[2] B=B[2] S=hfn_ipo_n1 
Xi_0_1 MUX2_X1 $PINS Z=Out[1] A=A[1] B=B[1] S=hfn_ipo_n1 
Xi_0_0 MUX2_X1 $PINS Z=Out[0] A=A[0] B=B[0] S=hfn_ipo_n1 
Xhfn_ipo_c1 CLKBUF_X1 $PINS Z=hfn_ipo_n1 A=Sel 
.ENDS

.SUBCKT Multiplixer__parameterized0__0_193 A[24] A[23] A[22] A[21] A[20] A[19] 
+ A[18] A[17] A[16] A[15] A[14] A[13] A[12] A[11] A[10] A[9] A[8] A[7] A[6] 
+ A[5] A[4] A[3] A[2] A[1] A[0] B[24] B[23] B[22] B[21] B[20] B[19] B[18] B[17] 
+ B[16] B[15] B[14] B[13] B[12] B[11] B[10] B[9] B[8] B[7] B[6] B[5] B[4] B[3] 
+ B[2] B[1] B[0] Sel Out[24] Out[23] Out[22] Out[21] Out[20] Out[19] Out[18] 
+ Out[17] Out[16] Out[15] Out[14] Out[13] Out[12] Out[11] Out[10] Out[9] Out[8] 
+ Out[7] Out[6] Out[5] Out[4] Out[3] Out[2] Out[1] Out[0] 
Xi_0_23 MUX2_X1 $PINS Z=Out[24] A=A[24] B=B[24] S=Sel 
Xi_0_22 MUX2_X1 $PINS Z=Out[22] A=A[22] B=B[22] S=Sel 
Xi_0_21 MUX2_X1 $PINS Z=Out[21] A=A[21] B=B[21] S=Sel 
Xi_0_20 MUX2_X1 $PINS Z=Out[20] A=A[20] B=B[20] S=Sel 
Xi_0_19 MUX2_X1 $PINS Z=Out[19] A=A[19] B=B[19] S=Sel 
Xi_0_18 MUX2_X1 $PINS Z=Out[18] A=A[18] B=B[18] S=Sel 
Xi_0_17 MUX2_X1 $PINS Z=Out[17] A=A[17] B=B[17] S=Sel 
Xi_0_16 MUX2_X1 $PINS Z=Out[16] A=A[16] B=B[16] S=Sel 
Xi_0_15 MUX2_X1 $PINS Z=Out[15] A=A[15] B=B[15] S=Sel 
Xi_0_14 MUX2_X1 $PINS Z=Out[14] A=A[14] B=B[14] S=Sel 
Xi_0_13 MUX2_X1 $PINS Z=Out[13] A=A[13] B=B[13] S=Sel 
Xi_0_12 MUX2_X1 $PINS Z=Out[12] A=A[12] B=B[12] S=Sel 
Xi_0_11 MUX2_X1 $PINS Z=Out[11] A=A[11] B=B[11] S=Sel 
Xi_0_10 MUX2_X1 $PINS Z=Out[10] A=A[10] B=B[10] S=Sel 
Xi_0_9 MUX2_X1 $PINS Z=Out[9] A=A[9] B=B[9] S=Sel 
Xi_0_8 MUX2_X1 $PINS Z=Out[8] A=A[8] B=B[8] S=Sel 
Xi_0_7 MUX2_X1 $PINS Z=Out[7] A=A[7] B=B[7] S=Sel 
Xi_0_6 MUX2_X1 $PINS Z=Out[6] A=A[6] B=B[6] S=Sel 
Xi_0_5 MUX2_X1 $PINS Z=Out[5] A=A[5] B=B[5] S=Sel 
Xi_0_4 MUX2_X1 $PINS Z=Out[4] A=A[4] B=B[4] S=Sel 
Xi_0_3 MUX2_X1 $PINS Z=Out[3] A=A[3] B=B[3] S=Sel 
Xi_0_2 MUX2_X1 $PINS Z=Out[2] A=A[2] B=B[2] S=Sel 
Xi_0_1 MUX2_X1 $PINS Z=Out[1] A=A[1] B=B[1] S=Sel 
Xi_0_0 MUX2_X1 $PINS Z=Out[0] A=A[0] B=B[0] S=Sel 
.ENDS

.SUBCKT datapath__0_2 EB2[7] EB2[6] EB2[5] EB2[4] EB2[3] EB2[2] EB2[1] EB2[0] 
+ EB[7] EB[6] EB[5] EB[4] EB[3] EB[2] EB[1] EB[0] 
Xi_12 OR3_X1 $PINS ZN=n_5 A1=EB[2] A2=EB[1] A3=EB[0] 
Xi_11 OR2_X1 $PINS ZN=n_4 A1=n_5 A2=EB[3] 
Xi_10 OR2_X1 $PINS ZN=n_3 A1=n_4 A2=EB[4] 
Xi_9 OR2_X1 $PINS ZN=n_2 A1=n_3 A2=EB[5] 
Xi_8 NOR2_X1 $PINS ZN=n_1 A1=n_2 A2=EB[6] 
Xi_7 XNOR2_X1 $PINS ZN=EB2[7] A=EB[7] B=n_1 
Xi_6 XOR2_X1 $PINS Z=EB2[6] A=EB[6] B=n_2 
Xi_5 XOR2_X1 $PINS Z=EB2[5] A=EB[5] B=n_3 
Xi_4 XOR2_X1 $PINS Z=EB2[4] A=EB[4] B=n_4 
Xi_3 XOR2_X1 $PINS Z=EB2[3] A=EB[3] B=n_5 
Xi_2 OAI21_X1 $PINS ZN=n_0 A=EB[2] B1=EB[1] B2=EB[0] 
Xi_1 AND2_X1 $PINS ZN=EB2[2] A1=n_5 A2=n_0 
Xi_0 XOR2_X1 $PINS Z=EB2[1] A=EB[1] B=EB[0] 
.ENDS

.SUBCKT datapath in2[7] in2[6] in2[5] in2[4] in2[3] in2[2] in2[1] in2[0] in1[7] 
+ in1[6] in1[5] in1[4] in1[3] in1[2] in1[1] in1[0] p_0[8] p_0[7] p_0[6] p_0[5] 
+ p_0[4] p_0[3] p_0[2] p_0[1] p_0[0] 
Xi_7 FA_X1 $PINS CO=p_0[8] S=p_0[7] A=in2[7] B=in1[7] CI=n_6 
Xi_6 FA_X1 $PINS CO=n_6 S=p_0[6] A=in2[6] B=in1[6] CI=n_5 
Xi_5 FA_X1 $PINS CO=n_5 S=p_0[5] A=in2[5] B=in1[5] CI=n_4 
Xi_4 FA_X1 $PINS CO=n_4 S=p_0[4] A=in2[4] B=in1[4] CI=n_3 
Xi_3 FA_X1 $PINS CO=n_3 S=p_0[3] A=in2[3] B=in1[3] CI=n_2 
Xi_2 FA_X1 $PINS CO=n_2 S=p_0[2] A=in2[2] B=in1[2] CI=n_1 
Xi_1 FA_X1 $PINS CO=n_1 S=p_0[1] A=in2[1] B=in1[1] CI=n_0 
Xi_0 HA_X1 $PINS CO=n_0 S=p_0[0] A=in2[0] B=in1[0] 
.ENDS

.SUBCKT VerilogAdder in1[7] in1[6] in1[5] in1[4] in1[3] in1[2] in1[1] in1[0] 
+ in2[7] in2[6] in2[5] in2[4] in2[3] in2[2] in2[1] in2[0] sum[7] sum[6] sum[5] 
+ sum[4] sum[3] sum[2] sum[1] sum[0] carry 
Xi_0 datapath $PINS p_0[8]=carry p_0[7]=sum[7] p_0[6]=sum[6] p_0[5]=sum[5] 
+ p_0[4]=sum[4] p_0[3]=sum[3] p_0[2]=sum[2] p_0[1]=sum[1] p_0[0]=sum[0] 
+ in1[7]=in1[7] in1[6]=in1[6] in1[5]=in1[5] in1[4]=in1[4] in1[3]=in1[3] 
+ in1[2]=in1[2] in1[1]=in1[1] in1[0]=in1[0] in2[7]=in2[7] in2[6]=in2[6] 
+ in2[5]=in2[5] in2[4]=in2[4] in2[3]=in2[3] in2[2]=in2[2] in2[1]=in2[1] 
+ in2[0]=in2[0] 
.ENDS

.SUBCKT subtractor EA[7] EA[6] EA[5] EA[4] EA[3] EA[2] EA[1] EA[0] EB[7] EB[6] 
+ EB[5] EB[4] EB[3] EB[2] EB[1] EB[0] S2[7] S2[6] S2[5] S2[4] S2[3] S2[2] S2[1] 
+ S2[0] B2 
Xi_0_17 INV_X1 $PINS ZN=n_0_9 A=S[5] 
Xi_0_16 INV_X1 $PINS ZN=n_0_8 A=S[2] 
Xi_0_15 INV_X1 $PINS ZN=B2 A=B 
Xi_0_14 AND2_X1 $PINS ZN=n_0_7 A1=S2[0] A2=hfn_ipo_n3 
Xi_0_13 OAI21_X1 $PINS ZN=n_0_6 A=hfn_ipo_n3 B1=S[1] B2=S2[0] 
Xi_0_12 OAI21_X1 $PINS ZN=n_0_5 A=hfn_ipo_n3 B1=S[3] B2=S[2] 
Xi_0_11 NAND2_X1 $PINS ZN=n_0_4 A1=n_0_6 A2=n_0_5 
Xi_0_10 AOI21_X1 $PINS ZN=n_0_3 A=n_0_4 B1=S[4] B2=hfn_ipo_n3 
Xi_0_9 OAI21_X1 $PINS ZN=n_0_2 A=n_0_3 B1=n_0_9 B2=B 
Xi_0_8 AOI21_X1 $PINS ZN=n_0_1 A=n_0_2 B1=S[6] B2=hfn_ipo_n3 
Xi_0_7 XNOR2_X1 $PINS ZN=S2[7] A=S[7] B=n_0_1 
Xi_0_6 XOR2_X1 $PINS Z=S2[6] A=S[6] B=n_0_2 
Xi_0_5 XNOR2_X1 $PINS ZN=S2[5] A=S[5] B=n_0_3 
Xi_0_4 XOR2_X1 $PINS Z=S2[4] A=S[4] B=n_0_4 
Xi_0_3 OAI21_X1 $PINS ZN=n_0_0 A=n_0_6 B1=n_0_8 B2=B 
Xi_0_2 XOR2_X1 $PINS Z=S2[3] A=S[3] B=n_0_0 
Xi_0_1 XNOR2_X2 $PINS ZN=S2[2] A=S[2] B=n_0_6 
Xi_0_0 XOR2_X2 $PINS Z=S2[1] A=S[1] B=n_0_7 
Xi_3 datapath__0_2 $PINS EB2[7]=EB2[7] EB2[6]=EB2[6] EB2[5]=EB2[5] 
+ EB2[4]=EB2[4] EB2[3]=EB2[3] EB2[2]=EB2[2] EB2[1]=EB2[1] EB2[0]=uc_0 EB[7]=EB[7] 
+ EB[6]=EB[6] EB[5]=EB[5] EB[4]=EB[4] EB[3]=EB[3] EB[2]=EB[2] EB[1]=EB[1] 
+ EB[0]=EB[0] 
Xrc VerilogAdder $PINS carry=B sum[7]=S[7] sum[6]=S[6] sum[5]=S[5] sum[4]=S[4] 
+ sum[3]=S[3] sum[2]=S[2] sum[1]=S[1] sum[0]=S2[0] in1[7]=EA[7] in1[6]=EA[6] 
+ in1[5]=EA[5] in1[4]=EA[4] in1[3]=EA[3] in1[2]=EA[2] in1[1]=EA[1] in1[0]=EA[0] 
+ in2[7]=EB2[7] in2[6]=EB2[6] in2[5]=EB2[5] in2[4]=EB2[4] in2[3]=EB2[3] 
+ in2[2]=EB2[2] in2[1]=EB2[1] in2[0]=EB[0] 
Xhfn_ipo_c3 CLKBUF_X1 $PINS Z=hfn_ipo_n3 A=B2 
.ENDS

.SUBCKT floatingadder a[31] a[30] a[29] a[28] a[27] a[26] a[25] a[24] a[23] 
+ a[22] a[21] a[20] a[19] a[18] a[17] a[16] a[15] a[14] a[13] a[12] a[11] a[10] 
+ a[9] a[8] a[7] a[6] a[5] a[4] a[3] a[2] a[1] a[0] b[31] b[30] b[29] b[28] 
+ b[27] b[26] b[25] b[24] b[23] b[22] b[21] b[20] b[19] b[18] b[17] b[16] b[15] 
+ b[14] b[13] b[12] b[11] b[10] b[9] b[8] b[7] b[6] b[5] b[4] b[3] b[2] b[1] 
+ b[0] sum[31] sum[30] sum[29] sum[28] sum[27] sum[26] sum[25] sum[24] sum[23] 
+ sum[22] sum[21] sum[20] sum[19] sum[18] sum[17] sum[16] sum[15] sum[14] 
+ sum[13] sum[12] sum[11] sum[10] sum[9] sum[8] sum[7] sum[6] sum[5] sum[4] 
+ sum[3] sum[2] sum[1] sum[0] carry clk 
Xi_0_1_444 INV_X1 $PINS ZN=n_0_1_332 A=n_0_1_217 
Xi_0_1_443 INV_X1 $PINS ZN=n_0_1_331 A=n_0_1_219 
Xi_0_1_442 INV_X1 $PINS ZN=n_0_1_330 A=n_0_1_220 
Xi_0_1_441 INV_X1 $PINS ZN=n_0_1_329 A=shiftleftamount[4] 
Xi_0_1_440 INV_X1 $PINS ZN=n_0_1_328 A=shiftleftamount[3] 
Xi_0_1_439 INV_X1 $PINS ZN=n_0_1_327 A=shiftleftamount[2] 
Xi_0_1_438 INV_X1 $PINS ZN=n_0_1_326 A=shiftleftamount[1] 
Xi_0_1_437 INV_X1 $PINS ZN=n_0_1_325 A=shiftleftamount[0] 
Xi_0_1_436 INV_X1 $PINS ZN=n_0_1_324 A=unNormalizedSum[23] 
Xi_0_1_435 INV_X1 $PINS ZN=n_0_1_323 A=subsum[4] 
Xi_0_1_434 INV_X1 $PINS ZN=n_0_1_322 A=subsum[2] 
Xi_0_1_433 INV_X1 $PINS ZN=n_0_1_321 A=subsum[1] 
Xi_0_1_432 INV_X1 $PINS ZN=n_0_1_320 A=subsum[0] 
Xi_0_1_431 INV_X1 $PINS ZN=n_0_1_319 A=outToShift[24] 
Xi_0_1_430 INV_X1 $PINS ZN=n_0_1_318 A=outToShift[7] 
Xi_0_1_429 INV_X1 $PINS ZN=n_0_1_317 A=n_0_18 
Xi_0_1_428 INV_X1 $PINS ZN=n_0_1_316 A=n_0_17 
Xi_0_1_427 INV_X1 $PINS ZN=n_0_1_315 A=n_0_14 
Xi_0_1_426 NOR2_X1 $PINS ZN=n_0_1_314 A1=subsum[4] A2=subsum[3] 
Xi_0_1_425 NOR3_X2 $PINS ZN=n_0_1_313 A1=subsum[4] A2=subsum[3] A3=subsum[2] 
Xi_0_1_424 NOR3_X1 $PINS ZN=n_0_1_312 A1=subsum[7] A2=subsum[6] A3=subsum[5] 
Xi_0_1_423 NAND2_X1 $PINS ZN=n_0_1_311 A1=n_0_1_313 A2=n_0_1_312 
Xi_0_1_422 NOR3_X1 $PINS ZN=shiftedToAdd[23] A1=n_0_1_311 A2=subsum[0] 
+ A3=subsum[1] 
Xi_0_1_421 NOR2_X1 $PINS ZN=n_0_1_310 A1=subsum[0] A2=outToShift[22] 
Xi_0_1_420 NOR3_X1 $PINS ZN=shiftedToAdd[22] A1=n_0_1_311 A2=n_0_1_310 
+ A3=subsum[1] 
Xi_0_1_419 OAI21_X1 $PINS ZN=n_0_1_309 A=n_0_1_320 B1=outToShift[21] 
+ B2=subsum[1] 
Xi_0_1_418 NAND3_X1 $PINS ZN=n_0_1_308 A1=n_0_1_321 A2=subsum[0] 
+ A3=outToShift[22] 
Xi_0_1_417 AOI21_X1 $PINS ZN=shiftedToAdd[21] A=n_0_1_311 B1=n_0_1_309 
+ B2=n_0_1_308 
Xi_0_1_416 OAI21_X1 $PINS ZN=n_0_1_307 A=subsum[0] B1=outToShift[21] 
+ B2=subsum[1] 
Xi_0_1_415 MUX2_X1 $PINS Z=n_0_1_306 A=outToShift[20] B=outToShift[22] 
+ S=subsum[1] 
Xi_0_1_414 NAND2_X1 $PINS ZN=n_0_1_305 A1=n_0_1_320 A2=n_0_1_306 
Xi_0_1_413 AOI21_X1 $PINS ZN=shiftedToAdd[20] A=n_0_1_311 B1=n_0_1_307 
+ B2=n_0_1_305 
Xi_0_1_412 NOR2_X1 $PINS ZN=n_0_1_304 A1=subsum[2] A2=outToShift[19] 
Xi_0_1_411 INV_X1 $PINS ZN=n_0_1_303 A=n_0_1_304 
Xi_0_1_410 NOR3_X1 $PINS ZN=n_0_1_302 A1=subsum[4] A2=subsum[3] A3=subsum[1] 
Xi_0_1_409 AND2_X1 $PINS ZN=n_0_1_301 A1=subsum[1] A2=n_0_1_313 
Xi_0_1_408 AOI22_X1 $PINS ZN=n_0_1_300 A1=outToShift[21] A2=n_0_1_301 
+ B1=n_0_1_302 B2=n_0_1_303 
Xi_0_1_407 NAND2_X1 $PINS ZN=n_0_1_299 A1=n_0_1_312 A2=n_0_1_320 
Xi_0_1_406 NAND2_X1 $PINS ZN=n_0_1_298 A1=subsum[0] A2=n_0_1_312 
Xi_0_1_405 NAND2_X1 $PINS ZN=n_0_1_297 A1=n_0_1_306 A2=n_0_1_313 
Xi_0_1_404 OAI22_X1 $PINS ZN=shiftedToAdd[19] A1=n_0_1_300 A2=n_0_1_299 
+ B1=n_0_1_298 B2=n_0_1_297 
Xi_0_1_403 MUX2_X1 $PINS Z=n_0_1_296 A=outToShift[18] B=outToShift[22] 
+ S=subsum[2] 
Xi_0_1_402 AOI22_X1 $PINS ZN=n_0_1_295 A1=n_0_1_302 A2=n_0_1_296 B1=n_0_1_301 
+ B2=outToShift[20] 
Xi_0_1_401 OAI22_X1 $PINS ZN=shiftedToAdd[18] A1=n_0_1_300 A2=n_0_1_298 
+ B1=n_0_1_295 B2=n_0_1_299 
Xi_0_1_400 MUX2_X1 $PINS Z=n_0_1_294 A=outToShift[17] B=outToShift[21] 
+ S=subsum[2] 
Xi_0_1_399 NOR3_X1 $PINS ZN=n_0_1_293 A1=n_0_1_321 A2=subsum[3] A3=subsum[4] 
Xi_0_1_398 AOI22_X1 $PINS ZN=n_0_1_292 A1=n_0_1_302 A2=n_0_1_294 B1=n_0_1_293 
+ B2=n_0_1_303 
Xi_0_1_397 OAI22_X1 $PINS ZN=shiftedToAdd[17] A1=n_0_1_298 A2=n_0_1_295 
+ B1=n_0_1_292 B2=n_0_1_299 
Xi_0_1_396 MUX2_X1 $PINS Z=n_0_1_291 A=outToShift[16] B=outToShift[18] 
+ S=subsum[1] 
Xi_0_1_395 NOR3_X2 $PINS ZN=n_0_1_290 A1=n_0_1_322 A2=subsum[3] A3=subsum[4] 
Xi_0_1_394 AOI22_X1 $PINS ZN=n_0_1_289 A1=n_0_1_306 A2=n_0_1_290 B1=n_0_1_291 
+ B2=n_0_1_313 
Xi_0_1_393 OAI22_X1 $PINS ZN=shiftedToAdd[16] A1=n_0_1_298 A2=n_0_1_292 
+ B1=n_0_1_289 B2=n_0_1_299 
Xi_0_1_392 AND2_X1 $PINS ZN=n_0_1_288 A1=n_0_1_323 A2=subsum[3] 
Xi_0_1_391 INV_X1 $PINS ZN=n_0_1_287 A=n_0_1_288 
Xi_0_1_390 NOR2_X1 $PINS ZN=n_0_1_286 A1=n_0_1_287 A2=subsum[2] 
Xi_0_1_389 INV_X1 $PINS ZN=n_0_1_285 A=n_0_1_286 
Xi_0_1_388 NAND3_X1 $PINS ZN=n_0_1_284 A1=subsum[2] A2=outToShift[19] 
+ A3=n_0_1_314 
Xi_0_1_387 NAND2_X1 $PINS ZN=n_0_1_283 A1=n_0_1_323 A2=outToShift[15] 
Xi_0_1_386 OAI211_X1 $PINS ZN=n_0_1_282 A=n_0_1_285 B=n_0_1_284 C1=n_0_1_283 
+ C2=subsum[2] 
Xi_0_1_385 AOI22_X1 $PINS ZN=n_0_1_281 A1=n_0_1_282 A2=n_0_1_321 B1=n_0_1_293 
+ B2=n_0_1_294 
Xi_0_1_384 OAI22_X1 $PINS ZN=shiftedToAdd[15] A1=n_0_1_281 A2=n_0_1_299 
+ B1=n_0_1_298 B2=n_0_1_289 
Xi_0_1_383 AOI222_X1 $PINS ZN=n_0_1_280 A1=outToShift[14] A2=n_0_1_313 
+ B1=n_0_1_290 B2=outToShift[18] C1=outToShift[22] C2=n_0_1_286 
Xi_0_1_382 NOR2_X1 $PINS ZN=n_0_1_279 A1=n_0_1_280 A2=subsum[1] 
Xi_0_1_381 MUX2_X1 $PINS Z=n_0_1_278 A=outToShift[16] B=outToShift[20] 
+ S=subsum[2] 
Xi_0_1_380 AOI21_X1 $PINS ZN=n_0_1_277 A=n_0_1_279 B1=n_0_1_278 B2=n_0_1_293 
Xi_0_1_379 OAI22_X1 $PINS ZN=shiftedToAdd[14] A1=n_0_1_277 A2=n_0_1_299 
+ B1=n_0_1_281 B2=n_0_1_298 
Xi_0_1_378 AOI222_X1 $PINS ZN=n_0_1_276 A1=outToShift[13] A2=n_0_1_313 
+ B1=n_0_1_290 B2=outToShift[17] C1=outToShift[21] C2=n_0_1_286 
Xi_0_1_377 NAND2_X1 $PINS ZN=n_0_1_275 A1=n_0_1_321 A2=n_0_1_276 
Xi_0_1_376 OAI21_X1 $PINS ZN=n_0_1_274 A=n_0_1_275 B1=n_0_1_282 B2=n_0_1_321 
Xi_0_1_375 OAI22_X1 $PINS ZN=shiftedToAdd[13] A1=n_0_1_277 A2=n_0_1_298 
+ B1=n_0_1_299 B2=n_0_1_274 
Xi_0_1_374 AOI222_X1 $PINS ZN=n_0_1_273 A1=outToShift[12] A2=n_0_1_313 
+ B1=n_0_1_290 B2=outToShift[16] C1=outToShift[20] C2=n_0_1_286 
Xi_0_1_373 MUX2_X1 $PINS Z=n_0_1_272 A=n_0_1_280 B=n_0_1_273 S=n_0_1_321 
Xi_0_1_372 OAI22_X1 $PINS ZN=shiftedToAdd[12] A1=n_0_1_272 A2=n_0_1_299 
+ B1=n_0_1_274 B2=n_0_1_298 
Xi_0_1_371 MUX2_X1 $PINS Z=n_0_1_271 A=outToShift[11] B=outToShift[15] 
+ S=subsum[2] 
Xi_0_1_370 NAND2_X1 $PINS ZN=n_0_1_270 A1=subsum[3] A2=n_0_1_304 
Xi_0_1_369 OAI211_X1 $PINS ZN=n_0_1_269 A=n_0_1_323 B=n_0_1_270 C1=n_0_1_271 
+ C2=subsum[3] 
Xi_0_1_368 MUX2_X1 $PINS Z=n_0_1_268 A=n_0_1_269 B=n_0_1_276 S=subsum[1] 
Xi_0_1_367 OAI22_X1 $PINS ZN=shiftedToAdd[11] A1=n_0_1_298 A2=n_0_1_272 
+ B1=n_0_1_268 B2=n_0_1_299 
Xi_0_1_366 AOI222_X1 $PINS ZN=n_0_1_267 A1=n_0_1_296 A2=n_0_1_288 B1=n_0_1_290 
+ B2=outToShift[14] C1=n_0_1_313 C2=outToShift[10] 
Xi_0_1_365 MUX2_X1 $PINS Z=n_0_1_266 A=n_0_1_267 B=n_0_1_273 S=subsum[1] 
Xi_0_1_364 OAI22_X1 $PINS ZN=shiftedToAdd[10] A1=n_0_1_266 A2=n_0_1_299 
+ B1=n_0_1_268 B2=n_0_1_298 
Xi_0_1_363 AOI222_X1 $PINS ZN=n_0_1_265 A1=n_0_1_294 A2=n_0_1_288 B1=n_0_1_290 
+ B2=outToShift[13] C1=n_0_1_313 C2=outToShift[9] 
Xi_0_1_362 MUX2_X1 $PINS Z=n_0_1_264 A=n_0_1_269 B=n_0_1_265 S=n_0_1_321 
Xi_0_1_361 OAI22_X1 $PINS ZN=shiftedToAdd[9] A1=n_0_1_266 A2=n_0_1_298 
+ B1=n_0_1_299 B2=n_0_1_264 
Xi_0_1_360 AOI222_X1 $PINS ZN=n_0_1_263 A1=n_0_1_278 A2=n_0_1_288 B1=n_0_1_313 
+ B2=outToShift[8] C1=n_0_1_290 C2=outToShift[12] 
Xi_0_1_359 MUX2_X1 $PINS Z=n_0_1_262 A=n_0_1_267 B=n_0_1_263 S=n_0_1_321 
Xi_0_1_358 OAI22_X1 $PINS ZN=shiftedToAdd[8] A1=n_0_1_262 A2=n_0_1_299 
+ B1=n_0_1_264 B2=n_0_1_298 
Xi_0_1_357 NOR2_X1 $PINS ZN=n_0_1_261 A1=n_0_1_323 A2=subsum[3] 
Xi_0_1_356 AOI22_X1 $PINS ZN=n_0_1_260 A1=n_0_1_318 A2=n_0_1_314 B1=n_0_1_283 
+ B2=subsum[3] 
Xi_0_1_355 NOR2_X1 $PINS ZN=n_0_1_259 A1=n_0_1_322 A2=n_0_1_287 
Xi_0_1_354 AOI222_X1 $PINS ZN=n_0_1_258 A1=n_0_1_322 A2=n_0_1_260 B1=n_0_1_259 
+ B2=outToShift[19] C1=outToShift[11] C2=n_0_1_290 
Xi_0_1_353 MUX2_X1 $PINS Z=n_0_1_257 A=n_0_1_265 B=n_0_1_258 S=n_0_1_321 
Xi_0_1_352 OAI22_X1 $PINS ZN=shiftedToAdd[7] A1=n_0_1_298 A2=n_0_1_262 
+ B1=n_0_1_257 B2=n_0_1_299 
Xi_0_1_351 AOI22_X1 $PINS ZN=n_0_1_256 A1=outToShift[6] A2=n_0_1_314 
+ B1=n_0_1_288 B2=outToShift[14] 
Xi_0_1_350 NAND2_X1 $PINS ZN=n_0_1_255 A1=outToShift[22] A2=n_0_1_261 
Xi_0_1_349 NAND2_X1 $PINS ZN=n_0_1_254 A1=n_0_1_256 A2=n_0_1_255 
Xi_0_1_348 AOI222_X1 $PINS ZN=n_0_1_253 A1=n_0_1_254 A2=n_0_1_322 
+ B1=outToShift[10] B2=n_0_1_290 C1=outToShift[18] C2=n_0_1_259 
Xi_0_1_347 MUX2_X1 $PINS Z=n_0_1_252 A=n_0_1_263 B=n_0_1_253 S=n_0_1_321 
Xi_0_1_346 OAI22_X1 $PINS ZN=shiftedToAdd[6] A1=n_0_1_298 A2=n_0_1_257 
+ B1=n_0_1_252 B2=n_0_1_299 
Xi_0_1_345 AOI22_X1 $PINS ZN=n_0_1_251 A1=outToShift[5] A2=n_0_1_314 
+ B1=n_0_1_288 B2=outToShift[13] 
Xi_0_1_344 NAND2_X1 $PINS ZN=n_0_1_250 A1=outToShift[21] A2=n_0_1_261 
Xi_0_1_343 NAND2_X1 $PINS ZN=n_0_1_249 A1=n_0_1_251 A2=n_0_1_250 
Xi_0_1_342 AOI222_X1 $PINS ZN=n_0_1_248 A1=n_0_1_249 A2=n_0_1_322 
+ B1=outToShift[9] B2=n_0_1_290 C1=outToShift[17] C2=n_0_1_259 
Xi_0_1_341 MUX2_X1 $PINS Z=n_0_1_247 A=n_0_1_258 B=n_0_1_248 S=n_0_1_321 
Xi_0_1_340 OAI22_X1 $PINS ZN=shiftedToAdd[5] A1=n_0_1_298 A2=n_0_1_252 
+ B1=n_0_1_247 B2=n_0_1_299 
Xi_0_1_339 AOI22_X1 $PINS ZN=n_0_1_246 A1=outToShift[4] A2=n_0_1_314 
+ B1=n_0_1_288 B2=outToShift[12] 
Xi_0_1_338 NAND2_X1 $PINS ZN=n_0_1_245 A1=outToShift[20] A2=n_0_1_261 
Xi_0_1_337 NAND2_X1 $PINS ZN=n_0_1_244 A1=n_0_1_246 A2=n_0_1_245 
Xi_0_1_336 AOI222_X1 $PINS ZN=n_0_1_243 A1=n_0_1_244 A2=n_0_1_322 
+ B1=outToShift[8] B2=n_0_1_290 C1=outToShift[16] C2=n_0_1_259 
Xi_0_1_335 MUX2_X1 $PINS Z=n_0_1_242 A=n_0_1_253 B=n_0_1_243 S=n_0_1_321 
Xi_0_1_334 OAI22_X1 $PINS ZN=shiftedToAdd[4] A1=n_0_1_298 A2=n_0_1_247 
+ B1=n_0_1_242 B2=n_0_1_299 
Xi_0_1_333 NAND2_X1 $PINS ZN=n_0_1_241 A1=subsum[2] A2=n_0_1_260 
Xi_0_1_332 NAND2_X1 $PINS ZN=n_0_1_240 A1=outToShift[19] A2=n_0_1_261 
Xi_0_1_331 OAI21_X1 $PINS ZN=n_0_1_239 A=n_0_1_241 B1=n_0_1_240 B2=subsum[2] 
Xi_0_1_330 AOI221_X1 $PINS ZN=n_0_1_238 A=n_0_1_239 B1=n_0_1_313 
+ B2=outToShift[3] C1=outToShift[11] C2=n_0_1_286 
Xi_0_1_329 MUX2_X1 $PINS Z=n_0_1_237 A=n_0_1_248 B=n_0_1_238 S=n_0_1_321 
Xi_0_1_328 OAI22_X1 $PINS ZN=shiftedToAdd[3] A1=n_0_1_298 A2=n_0_1_242 
+ B1=n_0_1_237 B2=n_0_1_299 
Xi_0_1_327 NOR3_X1 $PINS ZN=n_0_1_236 A1=n_0_1_323 A2=subsum[3] A3=subsum[2] 
Xi_0_1_326 AOI22_X1 $PINS ZN=n_0_1_235 A1=outToShift[2] A2=n_0_1_313 
+ B1=n_0_1_236 B2=outToShift[18] 
Xi_0_1_325 INV_X1 $PINS ZN=n_0_1_234 A=n_0_1_235 
Xi_0_1_324 AOI221_X1 $PINS ZN=n_0_1_233 A=n_0_1_234 B1=n_0_1_286 
+ B2=outToShift[10] C1=subsum[2] C2=n_0_1_254 
Xi_0_1_323 MUX2_X1 $PINS Z=n_0_1_232 A=n_0_1_233 B=n_0_1_243 S=subsum[1] 
Xi_0_1_322 OAI22_X1 $PINS ZN=shiftedToAdd[2] A1=n_0_1_298 A2=n_0_1_237 
+ B1=n_0_1_232 B2=n_0_1_299 
Xi_0_1_321 AOI22_X1 $PINS ZN=n_0_1_231 A1=outToShift[9] A2=n_0_1_286 
+ B1=n_0_1_236 B2=outToShift[17] 
Xi_0_1_320 INV_X1 $PINS ZN=n_0_1_230 A=n_0_1_231 
Xi_0_1_319 AOI221_X1 $PINS ZN=n_0_1_229 A=n_0_1_230 B1=n_0_1_313 
+ B2=outToShift[1] C1=subsum[2] C2=n_0_1_249 
Xi_0_1_318 MUX2_X1 $PINS Z=n_0_1_228 A=n_0_1_229 B=n_0_1_238 S=subsum[1] 
Xi_0_1_317 OAI22_X1 $PINS ZN=shiftedToAdd[1] A1=n_0_1_299 A2=n_0_1_228 
+ B1=n_0_1_232 B2=n_0_1_298 
Xi_0_1_316 AOI22_X1 $PINS ZN=n_0_1_227 A1=outToShift[0] A2=n_0_1_313 
+ B1=n_0_1_244 B2=subsum[2] 
Xi_0_1_315 AOI221_X1 $PINS ZN=n_0_1_226 A=subsum[1] B1=outToShift[8] 
+ B2=n_0_1_286 C1=n_0_1_236 C2=outToShift[16] 
Xi_0_1_314 AOI22_X1 $PINS ZN=n_0_1_225 A1=n_0_1_233 A2=subsum[1] B1=n_0_1_226 
+ B2=n_0_1_227 
Xi_0_1_313 INV_X1 $PINS ZN=n_0_1_224 A=n_0_1_225 
Xi_0_1_312 OAI22_X1 $PINS ZN=shiftedToAdd[0] A1=n_0_1_298 A2=n_0_1_228 
+ B1=n_0_1_224 B2=n_0_1_299 
Xi_0_1_311 NAND2_X1 $PINS ZN=n_0_1_223 A1=n_0_1_319 A2=outToAdd[24] 
Xi_0_1_310 NOR2_X1 $PINS ZN=n_0_1_222 A1=n_0_1_319 A2=outToAdd[24] 
Xi_0_1_309 INV_X1 $PINS ZN=n_0_1_221 A=n_0_1_222 
Xi_0_1_308 NAND2_X1 $PINS ZN=n_0_1_220 A1=n_0_1_223 A2=n_0_1_221 
Xi_0_1_307 NOR2_X2 $PINS ZN=n_0_1_219 A1=carryOfM A2=n_0_1_330 
Xi_0_1_306 NAND2_X1 $PINS ZN=n_0_1_218 A1=n_0_22 A2=n_0_1_219 
Xi_0_1_305 NOR2_X1 $PINS ZN=n_0_1_217 A1=n_0_1_220 A2=carryOfM 
Xi_0_1_304 XNOR2_X1 $PINS ZN=n_0_1_216 A=carryOfM B=n_0_1_330 
Xi_0_1_303 OAI21_X1 $PINS ZN=unNormalizedSum2[23] A=n_0_1_218 B1=n_0_1_216 
+ B2=n_0_1_324 
Xi_0_1_302 NAND2_X2 $PINS ZN=n_0_1_215 A1=carryOfM A2=n_0_1_330 
Xi_0_1_301 INV_X1 $PINS ZN=n_0_1_214 A=n_0_1_215 
Xi_0_1_300 OAI222_X1 $PINS ZN=n_0_1_213 A1=unNormalizedSum[22] A2=n_0_1_216 
+ B1=n_0_1_215 B2=unNormalizedSum[23] C1=n_0_1_331 C2=n_0_21 
Xi_0_1_299 INV_X1 $PINS ZN=unNormalizedSum2[22] A=n_0_1_213 
Xi_0_1_298 OAI222_X1 $PINS ZN=n_0_1_212 A1=unNormalizedSum[21] A2=n_0_1_216 
+ B1=n_0_1_215 B2=unNormalizedSum[22] C1=n_0_1_331 C2=n_0_20 
Xi_0_1_297 INV_X1 $PINS ZN=unNormalizedSum2[21] A=n_0_1_212 
Xi_0_1_296 OAI222_X1 $PINS ZN=n_0_1_211 A1=unNormalizedSum[20] A2=n_0_1_216 
+ B1=n_0_1_215 B2=unNormalizedSum[21] C1=n_0_1_331 C2=n_0_19 
Xi_0_1_295 INV_X1 $PINS ZN=unNormalizedSum2[20] A=n_0_1_211 
Xi_0_1_294 OAI22_X1 $PINS ZN=n_0_1_210 A1=unNormalizedSum[19] A2=n_0_1_216 
+ B1=n_0_1_215 B2=unNormalizedSum[20] 
Xi_0_1_293 AOI21_X1 $PINS ZN=unNormalizedSum2[19] A=n_0_1_210 B1=n_0_1_219 
+ B2=n_0_1_317 
Xi_0_1_292 OAI22_X1 $PINS ZN=n_0_1_209 A1=unNormalizedSum[18] A2=n_0_1_216 
+ B1=n_0_1_215 B2=unNormalizedSum[19] 
Xi_0_1_291 AOI21_X1 $PINS ZN=unNormalizedSum2[18] A=n_0_1_209 B1=n_0_1_219 
+ B2=n_0_1_316 
Xi_0_1_290 OAI222_X1 $PINS ZN=n_0_1_208 A1=unNormalizedSum[17] A2=n_0_1_216 
+ B1=n_0_1_215 B2=unNormalizedSum[18] C1=n_0_1_331 C2=n_0_16 
Xi_0_1_289 INV_X1 $PINS ZN=unNormalizedSum2[17] A=n_0_1_208 
Xi_0_1_288 OAI222_X1 $PINS ZN=n_0_1_207 A1=unNormalizedSum[16] A2=n_0_1_216 
+ B1=n_0_1_215 B2=unNormalizedSum[17] C1=n_0_1_331 C2=n_0_15 
Xi_0_1_287 INV_X1 $PINS ZN=unNormalizedSum2[16] A=n_0_1_207 
Xi_0_1_286 OAI22_X1 $PINS ZN=n_0_1_206 A1=unNormalizedSum[15] A2=n_0_1_216 
+ B1=n_0_1_215 B2=unNormalizedSum[16] 
Xi_0_1_285 AOI21_X1 $PINS ZN=unNormalizedSum2[15] A=n_0_1_206 B1=n_0_1_219 
+ B2=n_0_1_315 
Xi_0_1_284 MUX2_X1 $PINS Z=n_0_1_205 A=unNormalizedSum[14] B=n_0_13 S=n_0_1_219 
Xi_0_1_283 MUX2_X1 $PINS Z=unNormalizedSum2[14] A=unNormalizedSum[15] 
+ B=n_0_1_205 S=n_0_1_215 
Xi_0_1_282 MUX2_X1 $PINS Z=n_0_1_204 A=unNormalizedSum[13] B=n_0_12 S=n_0_1_219 
Xi_0_1_281 MUX2_X1 $PINS Z=unNormalizedSum2[13] A=unNormalizedSum[14] 
+ B=n_0_1_204 S=n_0_1_215 
Xi_0_1_280 MUX2_X1 $PINS Z=n_0_1_203 A=unNormalizedSum[12] B=n_0_11 S=n_0_1_219 
Xi_0_1_279 MUX2_X1 $PINS Z=unNormalizedSum2[12] A=unNormalizedSum[13] 
+ B=n_0_1_203 S=n_0_1_215 
Xi_0_1_278 MUX2_X1 $PINS Z=n_0_1_202 A=unNormalizedSum[11] B=n_0_10 S=n_0_1_219 
Xi_0_1_277 MUX2_X1 $PINS Z=unNormalizedSum2[11] A=unNormalizedSum[12] 
+ B=n_0_1_202 S=n_0_1_215 
Xi_0_1_276 MUX2_X1 $PINS Z=n_0_1_201 A=unNormalizedSum[10] B=n_0_9 S=n_0_1_219 
Xi_0_1_275 MUX2_X1 $PINS Z=unNormalizedSum2[10] A=unNormalizedSum[11] 
+ B=n_0_1_201 S=n_0_1_215 
Xi_0_1_274 MUX2_X1 $PINS Z=n_0_1_200 A=unNormalizedSum[9] B=n_0_8 S=n_0_1_219 
Xi_0_1_273 MUX2_X1 $PINS Z=unNormalizedSum2[9] A=unNormalizedSum[10] 
+ B=n_0_1_200 S=n_0_1_215 
Xi_0_1_272 MUX2_X1 $PINS Z=n_0_1_199 A=unNormalizedSum[8] B=n_0_7 S=n_0_1_219 
Xi_0_1_271 MUX2_X1 $PINS Z=unNormalizedSum2[8] A=unNormalizedSum[9] B=n_0_1_199 
+ S=n_0_1_215 
Xi_0_1_270 NOR2_X1 $PINS ZN=n_0_1_198 A1=n_0_1_215 A2=unNormalizedSum[8] 
Xi_0_1_269 MUX2_X1 $PINS Z=n_0_1_197 A=unNormalizedSum[7] B=n_0_6 S=n_0_1_219 
Xi_0_1_268 INV_X1 $PINS ZN=n_0_1_196 A=n_0_1_197 
Xi_0_1_267 AOI21_X1 $PINS ZN=unNormalizedSum2[7] A=n_0_1_198 B1=n_0_1_196 
+ B2=n_0_1_215 
Xi_0_1_266 NOR2_X1 $PINS ZN=n_0_1_195 A1=n_0_1_215 A2=unNormalizedSum[7] 
Xi_0_1_265 AND2_X1 $PINS ZN=n_0_1_194 A1=n_0_5 A2=n_0_1_219 
Xi_0_1_264 AOI21_X1 $PINS ZN=n_0_1_193 A=n_0_1_194 B1=n_0_1_331 
+ B2=unNormalizedSum[6] 
Xi_0_1_263 MUX2_X1 $PINS Z=n_0_1_192 A=unNormalizedSum[6] B=n_0_5 S=n_0_1_219 
Xi_0_1_262 AOI21_X1 $PINS ZN=unNormalizedSum2[6] A=n_0_1_195 B1=n_0_1_193 
+ B2=n_0_1_215 
Xi_0_1_261 MUX2_X1 $PINS Z=n_0_1_191 A=unNormalizedSum[5] B=n_0_4 S=n_0_1_219 
Xi_0_1_260 MUX2_X1 $PINS Z=unNormalizedSum2[5] A=unNormalizedSum[6] B=n_0_1_191 
+ S=n_0_1_215 
Xi_0_1_259 NOR2_X1 $PINS ZN=n_0_1_190 A1=n_0_1_215 A2=unNormalizedSum[5] 
Xi_0_1_258 MUX2_X1 $PINS Z=n_0_1_189 A=unNormalizedSum[4] B=n_0_3 S=n_0_1_219 
Xi_0_1_257 INV_X1 $PINS ZN=n_0_1_188 A=n_0_1_189 
Xi_0_1_256 AOI21_X1 $PINS ZN=unNormalizedSum2[4] A=n_0_1_190 B1=n_0_1_188 
+ B2=n_0_1_215 
Xi_0_1_255 MUX2_X1 $PINS Z=n_0_1_187 A=unNormalizedSum[3] B=n_0_2 S=n_0_1_219 
Xi_0_1_254 MUX2_X1 $PINS Z=unNormalizedSum2[3] A=unNormalizedSum[4] B=n_0_1_187 
+ S=n_0_1_215 
Xi_0_1_253 NOR2_X1 $PINS ZN=n_0_1_186 A1=n_0_1_215 A2=unNormalizedSum[3] 
Xi_0_1_252 AND2_X1 $PINS ZN=n_0_1_185 A1=n_0_1 A2=n_0_1_219 
Xi_0_1_251 AOI21_X1 $PINS ZN=n_0_1_184 A=n_0_1_185 B1=n_0_1_331 
+ B2=unNormalizedSum[2] 
Xi_0_1_250 MUX2_X1 $PINS Z=n_0_1_183 A=unNormalizedSum[2] B=n_0_1 S=n_0_1_219 
Xi_0_1_249 AOI21_X1 $PINS ZN=unNormalizedSum2[2] A=n_0_1_186 B1=n_0_1_184 
+ B2=n_0_1_215 
Xi_0_1_248 NOR2_X1 $PINS ZN=n_0_1_182 A1=n_0_1_215 A2=unNormalizedSum[2] 
Xi_0_1_247 MUX2_X1 $PINS Z=n_0_1_181 A=unNormalizedSum[1] B=n_0_0 S=n_0_1_219 
Xi_0_1_246 INV_X1 $PINS ZN=n_0_1_180 A=n_0_1_181 
Xi_0_1_245 AOI21_X1 $PINS ZN=unNormalizedSum2[1] A=n_0_1_182 B1=n_0_1_180 
+ B2=n_0_1_215 
Xi_0_1_244 MUX2_X1 $PINS Z=unNormalizedSum2[0] A=unNormalizedSum[1] 
+ B=unNormalizedSum[0] S=n_0_1_215 
Xi_0_1_243 NAND2_X1 $PINS ZN=n_0_1_179 A1=outToShift[24] A2=outToAdd[24] 
Xi_0_1_242 NOR2_X1 $PINS ZN=n_0_1_178 A1=outToShift[24] A2=outToAdd[24] 
Xi_0_1_241 OAI21_X1 $PINS ZN=sum[31] A=n_0_1_179 B1=n_0_1_178 B2=carryOfM 
Xi_0_1_240 NAND2_X1 $PINS ZN=n_0_1_177 A1=n_0_1_327 A2=n_0_1_326 
Xi_0_1_239 NOR2_X1 $PINS ZN=n_0_1_176 A1=shiftleftamount[1] 
+ A2=shiftleftamount[0] 
Xi_0_1_238 NAND2_X1 $PINS ZN=n_0_1_175 A1=n_0_1_329 A2=n_0_1_328 
Xi_0_1_237 NOR2_X1 $PINS ZN=n_0_1_174 A1=n_0_1_177 A2=n_0_1_175 
Xi_0_1_236 NOR3_X1 $PINS ZN=n_0_1_173 A1=n_0_1_177 A2=shiftleftamount[0] 
+ A3=shiftleftamount[3] 
Xi_0_1_235 NAND2_X1 $PINS ZN=n_0_1_172 A1=n_0_1_174 A2=n_0_1_325 
Xi_0_1_234 XNOR2_X1 $PINS ZN=n_0_1_171 A=n_0_1_13 B=n_0_1_172 
Xi_0_1_233 NAND2_X1 $PINS ZN=n_0_1_170 A1=n_0_1_220 A2=n_0_1_171 
Xi_0_1_232 OAI21_X1 $PINS ZN=n_0_1_169 A=n_0_1_170 B1=n_0_1_220 B2=n_0_1_6 
Xi_0_1_231 XNOR2_X1 $PINS ZN=sum[30] A=ES[7] B=n_0_1_169 
Xi_0_1_230 MUX2_X1 $PINS Z=sum[29] A=n_0_1_20 B=n_0_1_27 S=n_0_1_220 
Xi_0_1_229 MUX2_X1 $PINS Z=sum[28] A=n_0_1_19 B=n_0_1_26 S=n_0_1_220 
Xi_0_1_228 MUX2_X1 $PINS Z=sum[27] A=n_0_1_18 B=n_0_1_25 S=n_0_1_220 
Xi_0_1_227 MUX2_X1 $PINS Z=sum[26] A=n_0_1_17 B=n_0_1_24 S=n_0_1_220 
Xi_0_1_226 MUX2_X1 $PINS Z=sum[25] A=n_0_1_16 B=n_0_1_23 S=n_0_1_220 
Xi_0_1_225 MUX2_X1 $PINS Z=sum[24] A=n_0_1_15 B=n_0_1_22 S=n_0_1_220 
Xi_0_1_224 MUX2_X1 $PINS Z=sum[23] A=n_0_1_14 B=n_0_1_21 S=n_0_1_220 
Xi_0_1_223 NOR2_X1 $PINS ZN=n_0_1_168 A1=n_0_1_219 A2=n_0_1_175 
Xi_0_1_222 NOR2_X1 $PINS ZN=n_0_1_167 A1=n_0_1_331 A2=n_0_1_175 
Xi_0_1_221 AOI221_X1 $PINS ZN=n_0_1_166 A=n_0_1_177 B1=n_0_1_168 
+ B2=unNormalizedSum[22] C1=n_0_1_167 C2=n_0_21 
Xi_0_1_220 NOR2_X1 $PINS ZN=n_0_1_165 A1=n_0_1_328 A2=shiftleftamount[4] 
Xi_0_1_219 NOR2_X1 $PINS ZN=n_0_1_164 A1=n_0_1_329 A2=shiftleftamount[3] 
Xi_0_1_218 AOI22_X1 $PINS ZN=n_0_1_163 A1=n_0_1_205 A2=n_0_1_165 B1=n_0_1_192 
+ B2=n_0_1_164 
Xi_0_1_217 NOR2_X2 $PINS ZN=n_0_1_162 A1=shiftleftamount[0] A2=n_0_1_330 
Xi_0_1_216 NAND2_X1 $PINS ZN=n_0_1_161 A1=n_0_1_325 A2=n_0_1_220 
Xi_0_1_215 AOI21_X1 $PINS ZN=n_0_1_160 A=n_0_1_161 B1=n_0_1_163 B2=n_0_1_166 
Xi_0_1_214 AOI22_X1 $PINS ZN=n_0_1_159 A1=unNormalizedSum[16] A2=n_0_1_168 
+ B1=n_0_1_164 B2=unNormalizedSum[0] 
Xi_0_1_213 INV_X1 $PINS ZN=n_0_1_158 A=n_0_1_159 
Xi_0_1_212 AOI221_X1 $PINS ZN=n_0_1_157 A=n_0_1_158 B1=n_0_1_167 B2=n_0_15 
+ C1=n_0_1_199 C2=n_0_1_165 
Xi_0_1_211 INV_X1 $PINS ZN=n_0_1_156 A=n_0_1_157 
Xi_0_1_210 MUX2_X1 $PINS Z=n_0_1_155 A=unNormalizedSum[20] B=n_0_19 S=n_0_1_219 
Xi_0_1_209 NOR2_X1 $PINS ZN=n_0_1_154 A1=n_0_1_175 A2=shiftleftamount[2] 
Xi_0_1_208 AOI221_X1 $PINS ZN=n_0_1_153 A=shiftleftamount[2] B1=n_0_1_203 
+ B2=n_0_1_165 C1=n_0_1_164 C2=n_0_1_189 
Xi_0_1_207 AOI21_X1 $PINS ZN=n_0_1_152 A=n_0_1_153 B1=n_0_1_157 
+ B2=shiftleftamount[2] 
Xi_0_1_206 AOI21_X1 $PINS ZN=n_0_1_151 A=n_0_1_152 B1=n_0_1_154 B2=n_0_1_155 
Xi_0_1_205 AOI22_X1 $PINS ZN=n_0_1_150 A1=unNormalizedSum[18] A2=n_0_1_168 
+ B1=n_0_1_167 B2=n_0_17 
Xi_0_1_204 AOI22_X1 $PINS ZN=n_0_1_149 A1=n_0_1_201 A2=n_0_1_165 B1=n_0_1_183 
+ B2=n_0_1_164 
Xi_0_1_203 NAND2_X1 $PINS ZN=n_0_1_148 A1=n_0_1_149 A2=n_0_1_150 
Xi_0_1_202 NAND2_X1 $PINS ZN=n_0_1_147 A1=n_0_1_151 A2=shiftleftamount[1] 
Xi_0_1_201 NAND2_X1 $PINS ZN=n_0_1_146 A1=n_0_1_326 A2=shiftleftamount[2] 
Xi_0_1_200 OAI211_X1 $PINS ZN=n_0_1_145 A=n_0_1_147 B=n_0_1_160 C1=n_0_1_148 
+ C2=n_0_1_146 
Xi_0_1_199 AOI222_X1 $PINS ZN=n_0_1_144 A1=n_0_1_197 A2=n_0_1_165 B1=n_0_1_168 
+ B2=unNormalizedSum[15] C1=n_0_1_167 C2=n_0_14 
Xi_0_1_198 NAND2_X1 $PINS ZN=n_0_1_143 A1=n_0_1_331 A2=unNormalizedSum[19] 
Xi_0_1_197 OAI21_X1 $PINS ZN=n_0_1_142 A=n_0_1_143 B1=n_0_1_331 B2=n_0_1_317 
Xi_0_1_196 AOI221_X1 $PINS ZN=n_0_1_141 A=shiftleftamount[2] B1=n_0_1_202 
+ B2=n_0_1_165 C1=n_0_1_164 C2=n_0_1_187 
Xi_0_1_195 AOI21_X1 $PINS ZN=n_0_1_140 A=n_0_1_141 B1=n_0_1_144 
+ B2=shiftleftamount[2] 
Xi_0_1_194 AOI21_X1 $PINS ZN=n_0_1_139 A=n_0_1_140 B1=n_0_1_142 B2=n_0_1_154 
Xi_0_1_193 NOR2_X2 $PINS ZN=n_0_1_138 A1=n_0_1_330 A2=n_0_1_325 
Xi_0_1_192 NAND2_X1 $PINS ZN=n_0_1_137 A1=n_0_1_220 A2=shiftleftamount[0] 
Xi_0_1_191 AOI221_X1 $PINS ZN=n_0_1_136 A=n_0_1_177 B1=n_0_1_168 
+ B2=unNormalizedSum[21] C1=n_0_1_167 C2=n_0_20 
Xi_0_1_190 AOI22_X1 $PINS ZN=n_0_1_135 A1=n_0_1_204 A2=n_0_1_165 B1=n_0_1_191 
+ B2=n_0_1_164 
Xi_0_1_189 AOI22_X1 $PINS ZN=n_0_1_134 A1=n_0_1_200 A2=n_0_1_165 B1=n_0_1_181 
+ B2=n_0_1_164 
Xi_0_1_188 AOI22_X1 $PINS ZN=n_0_1_133 A1=unNormalizedSum[17] A2=n_0_1_168 
+ B1=n_0_1_167 B2=n_0_16 
Xi_0_1_187 NAND2_X1 $PINS ZN=n_0_1_132 A1=n_0_1_134 A2=n_0_1_133 
Xi_0_1_186 NOR2_X1 $PINS ZN=n_0_1_131 A1=n_0_1_146 A2=n_0_1_132 
Xi_0_1_185 AOI221_X1 $PINS ZN=n_0_1_130 A=n_0_1_131 B1=n_0_1_135 B2=n_0_1_136 
+ C1=n_0_1_139 C2=shiftleftamount[1] 
Xi_0_1_184 AOI222_X1 $PINS ZN=n_0_1_129 A1=unNormalizedSum[22] A2=n_0_1_217 
+ B1=n_0_1_138 B2=n_0_1_130 C1=n_0_1_214 C2=unNormalizedSum[23] 
Xi_0_1_183 NAND2_X1 $PINS ZN=sum[22] A1=n_0_1_129 A2=n_0_1_145 
Xi_0_1_182 NAND2_X1 $PINS ZN=n_0_1_128 A1=shiftleftamount[3] A2=n_0_1_193 
Xi_0_1_181 OAI21_X1 $PINS ZN=n_0_1_127 A=n_0_1_128 B1=n_0_1_205 
+ B2=shiftleftamount[3] 
Xi_0_1_180 NOR2_X1 $PINS ZN=n_0_1_126 A1=n_0_1_327 A2=shiftleftamount[4] 
Xi_0_1_179 NAND2_X1 $PINS ZN=n_0_1_125 A1=n_0_1_329 A2=shiftleftamount[2] 
Xi_0_1_178 NOR2_X1 $PINS ZN=n_0_1_124 A1=n_0_1_127 A2=n_0_1_125 
Xi_0_1_177 NAND2_X1 $PINS ZN=n_0_1_123 A1=n_0_1_329 A2=n_0_1_327 
Xi_0_1_176 AOI21_X1 $PINS ZN=n_0_1_122 A=n_0_1_124 B1=n_0_1_148 B2=n_0_1_327 
Xi_0_1_175 MUX2_X1 $PINS Z=n_0_1_121 A=n_0_1_122 B=n_0_1_151 S=n_0_1_326 
Xi_0_1_174 AOI222_X1 $PINS ZN=n_0_1_120 A1=unNormalizedSum[21] A2=n_0_1_217 
+ B1=n_0_1_162 B2=n_0_1_130 C1=n_0_1_214 C2=unNormalizedSum[22] 
Xi_0_1_173 OAI21_X1 $PINS ZN=sum[21] A=n_0_1_120 B1=n_0_1_121 B2=n_0_1_137 
Xi_0_1_172 MUX2_X1 $PINS Z=n_0_1_119 A=n_0_1_204 B=n_0_1_191 
+ S=shiftleftamount[3] 
Xi_0_1_171 INV_X1 $PINS ZN=n_0_1_118 A=n_0_1_119 
Xi_0_1_170 NAND2_X1 $PINS ZN=n_0_1_117 A1=n_0_1_327 A2=n_0_1_132 
Xi_0_1_169 OAI21_X1 $PINS ZN=n_0_1_116 A=n_0_1_117 B1=n_0_1_118 B2=n_0_1_125 
Xi_0_1_168 NAND2_X1 $PINS ZN=n_0_1_115 A1=n_0_1_326 A2=n_0_1_139 
Xi_0_1_167 OAI21_X1 $PINS ZN=n_0_1_114 A=n_0_1_115 B1=n_0_1_116 B2=n_0_1_326 
Xi_0_1_166 AOI22_X1 $PINS ZN=n_0_1_113 A1=unNormalizedSum[20] A2=n_0_1_217 
+ B1=n_0_1_214 B2=unNormalizedSum[21] 
Xi_0_1_165 OAI221_X1 $PINS ZN=sum[20] A=n_0_1_113 B1=n_0_1_114 B2=n_0_1_137 
+ C1=n_0_1_121 C2=n_0_1_161 
Xi_0_1_164 NOR2_X1 $PINS ZN=n_0_1_112 A1=unNormalizedSum2[19] A2=n_0_1_220 
Xi_0_1_163 NOR2_X1 $PINS ZN=n_0_1_111 A1=n_0_1_203 A2=shiftleftamount[3] 
Xi_0_1_162 AOI21_X1 $PINS ZN=n_0_1_110 A=n_0_1_111 B1=n_0_1_188 
+ B2=shiftleftamount[3] 
Xi_0_1_161 AOI22_X1 $PINS ZN=n_0_1_109 A1=n_0_1_327 A2=n_0_1_156 B1=n_0_1_126 
+ B2=n_0_1_110 
Xi_0_1_160 MUX2_X1 $PINS Z=n_0_1_108 A=n_0_1_122 B=n_0_1_109 
+ S=shiftleftamount[1] 
Xi_0_1_159 AOI221_X1 $PINS ZN=sum[19] A=n_0_1_112 B1=n_0_1_108 B2=n_0_1_138 
+ C1=n_0_1_114 C2=n_0_1_162 
Xi_0_1_158 NOR2_X1 $PINS ZN=n_0_1_107 A1=unNormalizedSum2[18] A2=n_0_1_220 
Xi_0_1_157 OR2_X1 $PINS ZN=n_0_1_106 A1=n_0_1_202 A2=shiftleftamount[3] 
Xi_0_1_156 OAI21_X1 $PINS ZN=n_0_1_105 A=n_0_1_106 B1=n_0_1_187 B2=n_0_1_328 
Xi_0_1_155 OAI22_X1 $PINS ZN=n_0_1_104 A1=shiftleftamount[2] A2=n_0_1_144 
+ B1=n_0_1_125 B2=n_0_1_105 
Xi_0_1_154 OR2_X1 $PINS ZN=n_0_1_103 A1=n_0_1_116 A2=shiftleftamount[1] 
Xi_0_1_153 OAI21_X1 $PINS ZN=n_0_1_102 A=n_0_1_103 B1=n_0_1_104 B2=n_0_1_326 
Xi_0_1_152 AOI221_X1 $PINS ZN=sum[18] A=n_0_1_107 B1=n_0_1_102 B2=n_0_1_138 
+ C1=n_0_1_108 C2=n_0_1_162 
Xi_0_1_151 NAND2_X1 $PINS ZN=n_0_1_101 A1=n_0_1_328 A2=shiftleftamount[2] 
Xi_0_1_150 NAND2_X1 $PINS ZN=n_0_1_100 A1=shiftleftamount[3] A2=n_0_1_184 
Xi_0_1_149 OAI21_X1 $PINS ZN=n_0_1_99 A=n_0_1_100 B1=n_0_1_201 
+ B2=shiftleftamount[3] 
Xi_0_1_148 NOR2_X1 $PINS ZN=n_0_1_98 A1=n_0_1_326 A2=shiftleftamount[4] 
Xi_0_1_147 OAI22_X1 $PINS ZN=n_0_1_97 A1=n_0_1_127 A2=n_0_1_123 B1=n_0_1_99 
+ B2=n_0_1_125 
Xi_0_1_146 NAND2_X1 $PINS ZN=n_0_1_96 A1=n_0_1_326 A2=n_0_1_109 
Xi_0_1_145 OAI21_X1 $PINS ZN=n_0_1_95 A=n_0_1_96 B1=n_0_1_97 B2=n_0_1_326 
Xi_0_1_144 NOR2_X1 $PINS ZN=n_0_1_94 A1=unNormalizedSum2[17] A2=n_0_1_220 
Xi_0_1_143 AOI221_X1 $PINS ZN=sum[17] A=n_0_1_94 B1=n_0_1_102 B2=n_0_1_162 
+ C1=n_0_1_138 C2=n_0_1_95 
Xi_0_1_142 AOI22_X1 $PINS ZN=n_0_1_93 A1=unNormalizedSum[16] A2=n_0_1_217 
+ B1=n_0_1_214 B2=unNormalizedSum[17] 
Xi_0_1_141 NAND2_X1 $PINS ZN=n_0_1_92 A1=n_0_1_327 A2=n_0_1_119 
Xi_0_1_140 NOR2_X1 $PINS ZN=n_0_1_91 A1=n_0_1_200 A2=shiftleftamount[3] 
Xi_0_1_139 AOI21_X1 $PINS ZN=n_0_1_90 A=n_0_1_91 B1=n_0_1_180 
+ B2=shiftleftamount[3] 
Xi_0_1_138 INV_X1 $PINS ZN=n_0_1_89 A=n_0_1_90 
Xi_0_1_137 OAI21_X1 $PINS ZN=n_0_1_88 A=n_0_1_92 B1=n_0_1_89 B2=n_0_1_327 
Xi_0_1_136 AOI22_X1 $PINS ZN=n_0_1_87 A1=n_0_1_326 A2=n_0_1_104 B1=n_0_1_98 
+ B2=n_0_1_88 
Xi_0_1_135 OAI221_X1 $PINS ZN=sum[16] A=n_0_1_93 B1=n_0_1_87 B2=n_0_1_137 
+ C1=n_0_1_95 C2=n_0_1_161 
Xi_0_1_134 NOR2_X1 $PINS ZN=n_0_1_86 A1=unNormalizedSum2[15] A2=n_0_1_220 
Xi_0_1_133 OR2_X1 $PINS ZN=n_0_1_85 A1=n_0_1_199 A2=shiftleftamount[3] 
Xi_0_1_132 OAI21_X1 $PINS ZN=n_0_1_84 A=n_0_1_85 B1=unNormalizedSum[0] 
+ B2=n_0_1_328 
Xi_0_1_131 NAND2_X1 $PINS ZN=n_0_1_83 A1=n_0_1_327 A2=n_0_1_110 
Xi_0_1_130 OAI21_X1 $PINS ZN=n_0_1_82 A=n_0_1_83 B1=n_0_1_84 B2=n_0_1_327 
Xi_0_1_129 NOR2_X1 $PINS ZN=n_0_1_81 A1=shiftleftamount[4] 
+ A2=shiftleftamount[1] 
Xi_0_1_128 AOI22_X1 $PINS ZN=n_0_1_80 A1=n_0_1_98 A2=n_0_1_82 B1=n_0_1_97 
+ B2=n_0_1_326 
Xi_0_1_127 AOI221_X1 $PINS ZN=sum[15] A=n_0_1_86 B1=n_0_1_80 B2=n_0_1_138 
+ C1=n_0_1_87 C2=n_0_1_162 
Xi_0_1_126 OAI22_X1 $PINS ZN=n_0_1_79 A1=n_0_1_332 A2=n_0_1_205 B1=n_0_1_215 
+ B2=unNormalizedSum[15] 
Xi_0_1_125 OAI22_X1 $PINS ZN=n_0_1_78 A1=shiftleftamount[2] A2=n_0_1_105 
+ B1=n_0_1_101 B2=n_0_1_196 
Xi_0_1_124 AOI22_X1 $PINS ZN=n_0_1_77 A1=n_0_1_88 A2=n_0_1_81 B1=n_0_1_78 
+ B2=n_0_1_98 
Xi_0_1_123 AOI221_X1 $PINS ZN=sum[14] A=n_0_1_79 B1=n_0_1_80 B2=n_0_1_162 
+ C1=n_0_1_138 C2=n_0_1_77 
Xi_0_1_122 OAI22_X1 $PINS ZN=n_0_1_76 A1=n_0_1_332 A2=n_0_1_204 B1=n_0_1_215 
+ B2=unNormalizedSum[14] 
Xi_0_1_121 OAI22_X1 $PINS ZN=n_0_1_75 A1=n_0_1_99 A2=shiftleftamount[2] 
+ B1=n_0_1_101 B2=n_0_1_193 
Xi_0_1_120 OR2_X1 $PINS ZN=n_0_1_74 A1=n_0_1_82 A2=shiftleftamount[1] 
Xi_0_1_119 OAI211_X1 $PINS ZN=n_0_1_73 A=n_0_1_329 B=n_0_1_74 C1=n_0_1_75 
+ C2=n_0_1_326 
Xi_0_1_118 AOI221_X1 $PINS ZN=sum[13] A=n_0_1_76 B1=n_0_1_162 B2=n_0_1_77 
+ C1=n_0_1_73 C2=n_0_1_138 
Xi_0_1_117 OAI22_X1 $PINS ZN=n_0_1_72 A1=n_0_1_332 A2=n_0_1_203 B1=n_0_1_215 
+ B2=unNormalizedSum[13] 
Xi_0_1_116 NAND3_X1 $PINS ZN=n_0_1_71 A1=n_0_1_328 A2=n_0_1_191 
+ A3=shiftleftamount[2] 
Xi_0_1_115 OAI21_X1 $PINS ZN=n_0_1_70 A=n_0_1_71 B1=n_0_1_89 
+ B2=shiftleftamount[2] 
Xi_0_1_114 AOI22_X1 $PINS ZN=n_0_1_69 A1=n_0_1_81 A2=n_0_1_78 B1=n_0_1_70 
+ B2=n_0_1_98 
Xi_0_1_113 AOI221_X1 $PINS ZN=sum[12] A=n_0_1_72 B1=n_0_1_69 B2=n_0_1_138 
+ C1=n_0_1_73 C2=n_0_1_162 
Xi_0_1_112 OAI22_X1 $PINS ZN=n_0_1_68 A1=n_0_1_332 A2=n_0_1_202 B1=n_0_1_215 
+ B2=unNormalizedSum[12] 
Xi_0_1_111 OAI22_X1 $PINS ZN=n_0_1_67 A1=n_0_1_84 A2=shiftleftamount[2] 
+ B1=n_0_1_101 B2=n_0_1_188 
Xi_0_1_110 AOI22_X1 $PINS ZN=n_0_1_66 A1=n_0_1_67 A2=n_0_1_98 B1=n_0_1_75 
+ B2=n_0_1_81 
Xi_0_1_109 AOI221_X1 $PINS ZN=sum[11] A=n_0_1_68 B1=n_0_1_66 B2=n_0_1_138 
+ C1=n_0_1_69 C2=n_0_1_162 
Xi_0_1_108 NOR2_X1 $PINS ZN=n_0_1_65 A1=n_0_1_327 A2=n_0_1_175 
Xi_0_1_107 AOI22_X1 $PINS ZN=n_0_1_64 A1=n_0_1_197 A2=n_0_1_154 B1=n_0_1_187 
+ B2=n_0_1_65 
Xi_0_1_106 INV_X1 $PINS ZN=n_0_1_63 A=n_0_1_64 
Xi_0_1_105 AOI22_X1 $PINS ZN=n_0_1_62 A1=n_0_1_70 A2=n_0_1_81 
+ B1=shiftleftamount[1] B2=n_0_1_63 
Xi_0_1_104 OAI22_X1 $PINS ZN=n_0_1_61 A1=n_0_1_332 A2=n_0_1_201 B1=n_0_1_215 
+ B2=unNormalizedSum[11] 
Xi_0_1_103 AOI221_X1 $PINS ZN=sum[10] A=n_0_1_61 B1=n_0_1_62 B2=n_0_1_138 
+ C1=n_0_1_162 C2=n_0_1_66 
Xi_0_1_102 AOI22_X1 $PINS ZN=n_0_1_60 A1=n_0_1_192 A2=n_0_1_154 B1=n_0_1_183 
+ B2=n_0_1_65 
Xi_0_1_101 INV_X1 $PINS ZN=n_0_1_59 A=n_0_1_60 
Xi_0_1_100 AOI22_X1 $PINS ZN=n_0_1_58 A1=n_0_1_67 A2=n_0_1_81 
+ B1=shiftleftamount[1] B2=n_0_1_59 
Xi_0_1_99 OAI22_X1 $PINS ZN=n_0_1_57 A1=n_0_1_332 A2=n_0_1_200 B1=n_0_1_215 
+ B2=unNormalizedSum[10] 
Xi_0_1_98 AOI221_X1 $PINS ZN=sum[9] A=n_0_1_57 B1=n_0_1_58 B2=n_0_1_138 
+ C1=n_0_1_162 C2=n_0_1_62 
Xi_0_1_97 AOI22_X1 $PINS ZN=n_0_1_56 A1=n_0_1_191 A2=n_0_1_154 B1=n_0_1_181 
+ B2=n_0_1_65 
Xi_0_1_96 NAND2_X1 $PINS ZN=n_0_1_55 A1=n_0_1_56 A2=shiftleftamount[1] 
Xi_0_1_95 OAI21_X1 $PINS ZN=n_0_1_54 A=n_0_1_55 B1=n_0_1_63 
+ B2=shiftleftamount[1] 
Xi_0_1_94 OAI22_X1 $PINS ZN=n_0_1_53 A1=n_0_1_332 A2=n_0_1_199 B1=n_0_1_215 
+ B2=unNormalizedSum[9] 
Xi_0_1_93 AOI221_X1 $PINS ZN=sum[8] A=n_0_1_53 B1=n_0_1_54 B2=n_0_1_138 
+ C1=n_0_1_162 C2=n_0_1_58 
Xi_0_1_92 AOI22_X1 $PINS ZN=n_0_1_52 A1=n_0_1_189 A2=n_0_1_154 B1=n_0_1_65 
+ B2=unNormalizedSum[0] 
Xi_0_1_91 INV_X1 $PINS ZN=n_0_1_51 A=n_0_1_52 
Xi_0_1_90 NAND2_X1 $PINS ZN=n_0_1_50 A1=n_0_1_52 A2=shiftleftamount[1] 
Xi_0_1_89 OAI21_X1 $PINS ZN=n_0_1_49 A=n_0_1_50 B1=n_0_1_59 
+ B2=shiftleftamount[1] 
Xi_0_1_88 OAI22_X1 $PINS ZN=n_0_1_48 A1=n_0_1_332 A2=n_0_1_197 B1=n_0_1_215 
+ B2=unNormalizedSum[8] 
Xi_0_1_87 AOI221_X1 $PINS ZN=sum[7] A=n_0_1_48 B1=n_0_1_49 B2=n_0_1_138 
+ C1=n_0_1_162 C2=n_0_1_54 
Xi_0_1_86 OAI22_X1 $PINS ZN=n_0_1_47 A1=n_0_1_332 A2=n_0_1_192 B1=n_0_1_215 
+ B2=unNormalizedSum[7] 
Xi_0_1_85 NOR3_X1 $PINS ZN=n_0_1_46 A1=n_0_1_175 A2=shiftleftamount[2] 
+ A3=n_0_1_326 
Xi_0_1_84 NOR2_X1 $PINS ZN=n_0_1_45 A1=n_0_1_56 A2=shiftleftamount[1] 
Xi_0_1_83 AOI21_X1 $PINS ZN=n_0_1_44 A=n_0_1_45 B1=n_0_1_46 B2=n_0_1_187 
Xi_0_1_82 AOI221_X1 $PINS ZN=sum[6] A=n_0_1_47 B1=n_0_1_49 B2=n_0_1_162 
+ C1=n_0_1_44 C2=n_0_1_138 
Xi_0_1_81 OAI22_X1 $PINS ZN=n_0_1_43 A1=n_0_1_332 A2=n_0_1_191 B1=n_0_1_215 
+ B2=unNormalizedSum[6] 
Xi_0_1_80 AOI22_X1 $PINS ZN=n_0_1_42 A1=n_0_1_326 A2=n_0_1_51 B1=n_0_1_46 
+ B2=n_0_1_183 
Xi_0_1_79 AOI221_X1 $PINS ZN=sum[5] A=n_0_1_43 B1=n_0_1_42 B2=n_0_1_138 
+ C1=n_0_1_44 C2=n_0_1_162 
Xi_0_1_78 AOI22_X1 $PINS ZN=n_0_1_41 A1=n_0_1_187 A2=n_0_1_174 B1=n_0_1_181 
+ B2=n_0_1_46 
Xi_0_1_77 AOI22_X1 $PINS ZN=n_0_1_40 A1=n_0_1_189 A2=n_0_1_217 
+ B1=unNormalizedSum[5] B2=n_0_1_214 
Xi_0_1_76 OAI221_X1 $PINS ZN=sum[4] A=n_0_1_40 B1=n_0_1_41 B2=n_0_1_137 
+ C1=n_0_1_161 C2=n_0_1_42 
Xi_0_1_75 AOI22_X1 $PINS ZN=n_0_1_39 A1=n_0_1_183 A2=n_0_1_174 B1=n_0_1_46 
+ B2=unNormalizedSum[0] 
Xi_0_1_74 AOI22_X1 $PINS ZN=n_0_1_38 A1=n_0_1_187 A2=n_0_1_217 
+ B1=unNormalizedSum[4] B2=n_0_1_214 
Xi_0_1_73 OAI221_X1 $PINS ZN=sum[3] A=n_0_1_38 B1=n_0_1_39 B2=n_0_1_137 
+ C1=n_0_1_161 C2=n_0_1_41 
Xi_0_1_72 NOR3_X1 $PINS ZN=n_0_1_37 A1=n_0_1_177 A2=n_0_1_175 A3=n_0_1_137 
Xi_0_1_71 AOI22_X1 $PINS ZN=n_0_1_36 A1=n_0_1_181 A2=n_0_1_37 
+ B1=unNormalizedSum[3] B2=n_0_1_214 
Xi_0_1_70 OAI221_X1 $PINS ZN=sum[2] A=n_0_1_36 B1=n_0_1_332 B2=n_0_1_184 
+ C1=n_0_1_39 C2=n_0_1_161 
Xi_0_1_69 AOI21_X1 $PINS ZN=n_0_1_35 A=n_0_1_217 B1=n_0_1_174 B2=n_0_1_162 
Xi_0_1_68 AOI22_X1 $PINS ZN=n_0_1_34 A1=unNormalizedSum[2] A2=n_0_1_214 
+ B1=n_0_1_37 B2=unNormalizedSum[0] 
Xi_0_1_67 OAI21_X1 $PINS ZN=sum[1] A=n_0_1_34 B1=n_0_1_35 B2=n_0_1_180 
Xi_0_1_66 NAND2_X1 $PINS ZN=n_0_1_33 A1=n_0_1_220 A2=n_0_1_172 
Xi_0_1_65 AND2_X1 $PINS ZN=sum[0] A1=unNormalizedSum2[0] A2=n_0_1_33 
Xi_0_1_64 MUX2_X1 $PINS Z=comA[23] A=n_0_45 B=shiftedToAdd[23] S=n_0_1_221 
Xi_0_1_63 MUX2_X1 $PINS Z=comA[22] A=n_0_44 B=shiftedToAdd[22] S=n_0_1_221 
Xi_0_1_62 MUX2_X1 $PINS Z=comA[21] A=n_0_43 B=shiftedToAdd[21] S=n_0_1_221 
Xi_0_1_61 MUX2_X1 $PINS Z=comA[20] A=n_0_42 B=shiftedToAdd[20] S=n_0_1_221 
Xi_0_1_60 MUX2_X1 $PINS Z=comA[19] A=n_0_41 B=shiftedToAdd[19] S=n_0_1_221 
Xi_0_1_59 MUX2_X1 $PINS Z=comA[18] A=n_0_40 B=shiftedToAdd[18] S=n_0_1_221 
Xi_0_1_58 MUX2_X1 $PINS Z=comA[17] A=n_0_39 B=shiftedToAdd[17] S=n_0_1_221 
Xi_0_1_57 MUX2_X1 $PINS Z=comA[16] A=n_0_38 B=shiftedToAdd[16] S=n_0_1_221 
Xi_0_1_56 MUX2_X1 $PINS Z=comA[15] A=n_0_37 B=shiftedToAdd[15] S=n_0_1_221 
Xi_0_1_55 MUX2_X1 $PINS Z=comA[14] A=n_0_36 B=shiftedToAdd[14] S=n_0_1_221 
Xi_0_1_54 MUX2_X1 $PINS Z=comA[13] A=n_0_35 B=shiftedToAdd[13] S=n_0_1_221 
Xi_0_1_53 MUX2_X1 $PINS Z=comA[12] A=n_0_34 B=shiftedToAdd[12] S=n_0_1_221 
Xi_0_1_52 MUX2_X1 $PINS Z=comA[11] A=n_0_33 B=shiftedToAdd[11] S=n_0_1_221 
Xi_0_1_51 MUX2_X1 $PINS Z=comA[10] A=n_0_32 B=shiftedToAdd[10] S=n_0_1_221 
Xi_0_1_50 MUX2_X1 $PINS Z=comA[9] A=n_0_31 B=shiftedToAdd[9] S=n_0_1_221 
Xi_0_1_49 MUX2_X1 $PINS Z=comA[8] A=n_0_30 B=shiftedToAdd[8] S=n_0_1_221 
Xi_0_1_48 MUX2_X1 $PINS Z=comA[7] A=n_0_29 B=shiftedToAdd[7] S=n_0_1_221 
Xi_0_1_47 MUX2_X1 $PINS Z=comA[6] A=n_0_28 B=shiftedToAdd[6] S=n_0_1_221 
Xi_0_1_46 MUX2_X1 $PINS Z=comA[5] A=n_0_27 B=shiftedToAdd[5] S=n_0_1_221 
Xi_0_1_45 MUX2_X1 $PINS Z=comA[4] A=n_0_26 B=shiftedToAdd[4] S=n_0_1_221 
Xi_0_1_44 MUX2_X1 $PINS Z=comA[3] A=n_0_25 B=shiftedToAdd[3] S=n_0_1_221 
Xi_0_1_43 MUX2_X1 $PINS Z=comA[2] A=n_0_24 B=shiftedToAdd[2] S=n_0_1_221 
Xi_0_1_42 MUX2_X1 $PINS Z=comA[1] A=n_0_23 B=shiftedToAdd[1] S=n_0_1_221 
Xi_0_1_41 OR2_X1 $PINS ZN=comB[23] A1=n_0_1_223 A2=n_0_68 
Xi_0_1_40 MUX2_X1 $PINS Z=comB[22] A=n_0_67 B=outToAdd[22] S=n_0_1_223 
Xi_0_1_39 MUX2_X1 $PINS Z=comB[21] A=n_0_66 B=outToAdd[21] S=n_0_1_223 
Xi_0_1_38 MUX2_X1 $PINS Z=comB[20] A=n_0_65 B=outToAdd[20] S=n_0_1_223 
Xi_0_1_37 MUX2_X1 $PINS Z=comB[19] A=n_0_64 B=outToAdd[19] S=n_0_1_223 
Xi_0_1_36 MUX2_X1 $PINS Z=comB[18] A=n_0_63 B=outToAdd[18] S=n_0_1_223 
Xi_0_1_35 MUX2_X1 $PINS Z=comB[17] A=n_0_62 B=outToAdd[17] S=n_0_1_223 
Xi_0_1_34 MUX2_X1 $PINS Z=comB[16] A=n_0_61 B=outToAdd[16] S=n_0_1_223 
Xi_0_1_33 MUX2_X1 $PINS Z=comB[15] A=n_0_60 B=outToAdd[15] S=n_0_1_223 
Xi_0_1_32 MUX2_X1 $PINS Z=comB[14] A=n_0_59 B=outToAdd[14] S=n_0_1_223 
Xi_0_1_31 MUX2_X1 $PINS Z=comB[13] A=n_0_58 B=outToAdd[13] S=n_0_1_223 
Xi_0_1_30 MUX2_X1 $PINS Z=comB[12] A=n_0_57 B=outToAdd[12] S=n_0_1_223 
Xi_0_1_29 MUX2_X1 $PINS Z=comB[11] A=n_0_56 B=outToAdd[11] S=n_0_1_223 
Xi_0_1_28 MUX2_X1 $PINS Z=comB[10] A=n_0_55 B=outToAdd[10] S=n_0_1_223 
Xi_0_1_27 MUX2_X1 $PINS Z=comB[9] A=n_0_54 B=outToAdd[9] S=n_0_1_223 
Xi_0_1_26 MUX2_X1 $PINS Z=comB[8] A=n_0_53 B=outToAdd[8] S=n_0_1_223 
Xi_0_1_25 MUX2_X1 $PINS Z=comB[7] A=n_0_52 B=outToAdd[7] S=n_0_1_223 
Xi_0_1_24 MUX2_X1 $PINS Z=comB[6] A=n_0_51 B=outToAdd[6] S=n_0_1_223 
Xi_0_1_23 MUX2_X1 $PINS Z=comB[5] A=n_0_50 B=outToAdd[5] S=n_0_1_223 
Xi_0_1_22 MUX2_X1 $PINS Z=comB[4] A=n_0_49 B=outToAdd[4] S=n_0_1_223 
Xi_0_1_21 MUX2_X1 $PINS Z=comB[3] A=n_0_48 B=outToAdd[3] S=n_0_1_223 
Xi_0_1_20 MUX2_X1 $PINS Z=comB[2] A=n_0_47 B=outToAdd[2] S=n_0_1_223 
Xi_0_1_19 MUX2_X1 $PINS Z=comB[1] A=n_0_46 B=outToAdd[1] S=n_0_1_223 
Xi_0_1_18 XNOR2_X1 $PINS ZN=n_0_1_32 A=n_0_1_326 B=shiftleftamount[0] 
Xi_0_1_17 XNOR2_X1 $PINS ZN=n_0_1_31 A=shiftleftamount[2] B=n_0_1_176 
Xi_0_1_16 AOI21_X1 $PINS ZN=n_0_1_30 A=n_0_1_328 B1=n_0_1_176 B2=n_0_1_327 
Xi_0_1_15 NOR2_X1 $PINS ZN=n_0_1_29 A1=n_0_1_173 A2=n_0_1_30 
Xi_0_1_14 XNOR2_X1 $PINS ZN=n_0_1_28 A=shiftleftamount[4] B=n_0_1_173 
Xi_0_1_13 FA_X1 $PINS CO=n_0_1_13 S=n_0_1_27 A=n_0_1_172 B=ES[6] CI=n_0_1_12 
Xi_0_1_12 FA_X1 $PINS CO=n_0_1_12 S=n_0_1_26 A=n_0_1_172 B=ES[5] CI=n_0_1_11 
Xi_0_1_11 FA_X1 $PINS CO=n_0_1_11 S=n_0_1_25 A=n_0_1_28 B=ES[4] CI=n_0_1_10 
Xi_0_1_10 FA_X1 $PINS CO=n_0_1_10 S=n_0_1_24 A=n_0_1_29 B=ES[3] CI=n_0_1_9 
Xi_0_1_9 FA_X1 $PINS CO=n_0_1_9 S=n_0_1_23 A=n_0_1_31 B=ES[2] CI=n_0_1_8 
Xi_0_1_8 FA_X1 $PINS CO=n_0_1_8 S=n_0_1_22 A=n_0_1_32 B=ES[1] CI=n_0_1_7 
Xi_0_1_7 HA_X1 $PINS CO=n_0_1_7 S=n_0_1_21 A=shiftleftamount[0] B=ES[0] 
Xi_0_1_6 HA_X1 $PINS CO=n_0_1_6 S=n_0_1_20 A=ES[6] B=n_0_1_5 
Xi_0_1_5 HA_X1 $PINS CO=n_0_1_5 S=n_0_1_19 A=ES[5] B=n_0_1_4 
Xi_0_1_4 HA_X1 $PINS CO=n_0_1_4 S=n_0_1_18 A=ES[4] B=n_0_1_3 
Xi_0_1_3 HA_X1 $PINS CO=n_0_1_3 S=n_0_1_17 A=ES[3] B=n_0_1_2 
Xi_0_1_2 HA_X1 $PINS CO=n_0_1_2 S=n_0_1_16 A=ES[2] B=n_0_1_1 
Xi_0_1_1 HA_X1 $PINS CO=n_0_1_1 S=n_0_1_15 A=ES[1] B=n_0_1_0 
Xi_0_1_0 HA_X1 $PINS CO=n_0_1_0 S=n_0_1_14 A=n_0_1_214 B=ES[0] 
Xi_0_15 datapath__0_27 $PINS p_0[23]=n_0_68 p_0[22]=n_0_67 p_0[21]=n_0_66 
+ p_0[20]=n_0_65 p_0[19]=n_0_64 p_0[18]=n_0_63 p_0[17]=n_0_62 p_0[16]=n_0_61 
+ p_0[15]=n_0_60 p_0[14]=n_0_59 p_0[13]=n_0_58 p_0[12]=n_0_57 p_0[11]=n_0_56 
+ p_0[10]=n_0_55 p_0[9]=n_0_54 p_0[8]=n_0_53 p_0[7]=n_0_52 p_0[6]=n_0_51 
+ p_0[5]=n_0_50 p_0[4]=n_0_49 p_0[3]=n_0_48 p_0[2]=n_0_47 p_0[1]=n_0_46 
+ p_0[0]=uc_8 outToAdd[23]=uc_9 outToAdd[22]=outToAdd[22] 
+ outToAdd[21]=outToAdd[21] outToAdd[20]=outToAdd[20] outToAdd[19]=outToAdd[19] 
+ outToAdd[18]=outToAdd[18] outToAdd[17]=outToAdd[17] outToAdd[16]=outToAdd[16] 
+ outToAdd[15]=outToAdd[15] outToAdd[14]=outToAdd[14] outToAdd[13]=outToAdd[13] 
+ outToAdd[12]=outToAdd[12] outToAdd[11]=outToAdd[11] outToAdd[10]=outToAdd[10] 
+ outToAdd[9]=outToAdd[9] outToAdd[8]=outToAdd[8] outToAdd[7]=outToAdd[7] 
+ outToAdd[6]=outToAdd[6] outToAdd[5]=outToAdd[5] outToAdd[4]=outToAdd[4] 
+ outToAdd[3]=outToAdd[3] outToAdd[2]=outToAdd[2] outToAdd[1]=outToAdd[1] 
+ outToAdd[0]=outToAdd[0] 
Xi_0_12 datapath__0_24 $PINS p_0[23]=n_0_45 p_0[22]=n_0_44 p_0[21]=n_0_43 
+ p_0[20]=n_0_42 p_0[19]=n_0_41 p_0[18]=n_0_40 p_0[17]=n_0_39 p_0[16]=n_0_38 
+ p_0[15]=n_0_37 p_0[14]=n_0_36 p_0[13]=n_0_35 p_0[12]=n_0_34 p_0[11]=n_0_33 
+ p_0[10]=n_0_32 p_0[9]=n_0_31 p_0[8]=n_0_30 p_0[7]=n_0_29 p_0[6]=n_0_28 
+ p_0[5]=n_0_27 p_0[4]=n_0_26 p_0[3]=n_0_25 p_0[2]=n_0_24 p_0[1]=n_0_23 
+ p_0[0]=uc_7 shiftedToAdd[23]=shiftedToAdd[23] shiftedToAdd[22]=shiftedToAdd[22] 
+ shiftedToAdd[21]=shiftedToAdd[21] shiftedToAdd[20]=shiftedToAdd[20] 
+ shiftedToAdd[19]=shiftedToAdd[19] shiftedToAdd[18]=shiftedToAdd[18] 
+ shiftedToAdd[17]=shiftedToAdd[17] shiftedToAdd[16]=shiftedToAdd[16] 
+ shiftedToAdd[15]=shiftedToAdd[15] shiftedToAdd[14]=shiftedToAdd[14] 
+ shiftedToAdd[13]=shiftedToAdd[13] shiftedToAdd[12]=shiftedToAdd[12] 
+ shiftedToAdd[11]=shiftedToAdd[11] shiftedToAdd[10]=shiftedToAdd[10] 
+ shiftedToAdd[9]=shiftedToAdd[9] shiftedToAdd[8]=shiftedToAdd[8] 
+ shiftedToAdd[7]=shiftedToAdd[7] shiftedToAdd[6]=shiftedToAdd[6] 
+ shiftedToAdd[5]=shiftedToAdd[5] shiftedToAdd[4]=shiftedToAdd[4] 
+ shiftedToAdd[3]=shiftedToAdd[3] shiftedToAdd[2]=shiftedToAdd[2] 
+ shiftedToAdd[1]=shiftedToAdd[1] shiftedToAdd[0]=shiftedToAdd[0] 
Xi_0_0 datapath__0_11 $PINS p_0[23]=n_0_22 p_0[22]=n_0_21 p_0[21]=n_0_20 
+ p_0[20]=n_0_19 p_0[19]=n_0_18 p_0[18]=n_0_17 p_0[17]=n_0_16 p_0[16]=n_0_15 
+ p_0[15]=n_0_14 p_0[14]=n_0_13 p_0[13]=n_0_12 p_0[12]=n_0_11 p_0[11]=n_0_10 
+ p_0[10]=n_0_9 p_0[9]=n_0_8 p_0[8]=n_0_7 p_0[7]=n_0_6 p_0[6]=n_0_5 p_0[5]=n_0_4 
+ p_0[4]=n_0_3 p_0[3]=n_0_2 p_0[2]=n_0_1 p_0[1]=n_0_0 p_0[0]=uc_6 
+ unNormalizedSum[23]=unNormalizedSum[23] unNormalizedSum[22]=unNormalizedSum[22] 
+ unNormalizedSum[21]=unNormalizedSum[21] unNormalizedSum[20]=unNormalizedSum[20] 
+ unNormalizedSum[19]=unNormalizedSum[19] unNormalizedSum[18]=unNormalizedSum[18] 
+ unNormalizedSum[17]=unNormalizedSum[17] unNormalizedSum[16]=unNormalizedSum[16] 
+ unNormalizedSum[15]=unNormalizedSum[15] unNormalizedSum[14]=unNormalizedSum[14] 
+ unNormalizedSum[13]=unNormalizedSum[13] unNormalizedSum[12]=unNormalizedSum[12] 
+ unNormalizedSum[11]=unNormalizedSum[11] unNormalizedSum[10]=unNormalizedSum[10] 
+ unNormalizedSum[9]=unNormalizedSum[9] unNormalizedSum[8]=unNormalizedSum[8] 
+ unNormalizedSum[7]=unNormalizedSum[7] unNormalizedSum[6]=unNormalizedSum[6] 
+ unNormalizedSum[5]=unNormalizedSum[5] unNormalizedSum[4]=unNormalizedSum[4] 
+ unNormalizedSum[3]=unNormalizedSum[3] unNormalizedSum[2]=unNormalizedSum[2] 
+ unNormalizedSum[1]=unNormalizedSum[1] unNormalizedSum[0]=unNormalizedSum[0] 
Xlz LZeros $PINS out[4]=shiftleftamount[4] out[3]=shiftleftamount[3] 
+ out[2]=shiftleftamount[2] out[1]=shiftleftamount[1] out[0]=shiftleftamount[0] 
+ in[23]=unNormalizedSum2[23] in[22]=unNormalizedSum2[22] 
+ in[21]=unNormalizedSum2[21] in[20]=unNormalizedSum2[20] 
+ in[19]=unNormalizedSum2[19] in[18]=unNormalizedSum2[18] 
+ in[17]=unNormalizedSum2[17] in[16]=unNormalizedSum2[16] 
+ in[15]=unNormalizedSum2[15] in[14]=unNormalizedSum2[14] 
+ in[13]=unNormalizedSum2[13] in[12]=unNormalizedSum2[12] 
+ in[11]=unNormalizedSum2[11] in[10]=unNormalizedSum2[10] 
+ in[9]=unNormalizedSum2[9] in[8]=unNormalizedSum2[8] in[7]=unNormalizedSum2[7] 
+ in[6]=unNormalizedSum2[6] in[5]=unNormalizedSum2[5] in[4]=unNormalizedSum2[4] 
+ in[3]=unNormalizedSum2[3] in[2]=unNormalizedSum2[2] in[1]=unNormalizedSum2[1] 
+ in[0]=unNormalizedSum2[0] 
Xmux0 Multiplixer $PINS Out[7]=ES[7] Out[6]=ES[6] Out[5]=ES[5] Out[4]=ES[4] 
+ Out[3]=ES[3] Out[2]=ES[2] Out[1]=ES[1] Out[0]=ES[0] A[7]=a[30] A[6]=a[29] 
+ A[5]=a[28] A[4]=a[27] A[3]=a[26] A[2]=a[25] A[1]=a[24] A[0]=a[23] B[7]=b[30] 
+ B[6]=b[29] B[5]=b[28] B[4]=b[27] B[3]=b[26] B[2]=b[25] B[1]=b[24] B[0]=b[23] 
+ Sel=hfn_ipo_n3 
Xrr CIA_24bit $PINS carry=carryOfM sum[23]=unNormalizedSum[23] 
+ sum[22]=unNormalizedSum[22] sum[21]=unNormalizedSum[21] 
+ sum[20]=unNormalizedSum[20] sum[19]=unNormalizedSum[19] 
+ sum[18]=unNormalizedSum[18] sum[17]=unNormalizedSum[17] 
+ sum[16]=unNormalizedSum[16] sum[15]=unNormalizedSum[15] 
+ sum[14]=unNormalizedSum[14] sum[13]=unNormalizedSum[13] 
+ sum[12]=unNormalizedSum[12] sum[11]=unNormalizedSum[11] 
+ sum[10]=unNormalizedSum[10] sum[9]=unNormalizedSum[9] sum[8]=unNormalizedSum[8] 
+ sum[7]=unNormalizedSum[7] sum[6]=unNormalizedSum[6] sum[5]=unNormalizedSum[5] 
+ sum[4]=unNormalizedSum[4] sum[3]=unNormalizedSum[3] sum[2]=unNormalizedSum[2] 
+ sum[1]=unNormalizedSum[1] sum[0]=unNormalizedSum[0] in1[23]=comA[23] 
+ in1[22]=comA[22] in1[21]=comA[21] in1[20]=comA[20] in1[19]=comA[19] 
+ in1[18]=comA[18] in1[17]=comA[17] in1[16]=comA[16] in1[15]=comA[15] 
+ in1[14]=comA[14] in1[13]=comA[13] in1[12]=comA[12] in1[11]=comA[11] 
+ in1[10]=comA[10] in1[9]=comA[9] in1[8]=comA[8] in1[7]=comA[7] in1[6]=comA[6] 
+ in1[5]=comA[5] in1[4]=comA[4] in1[3]=comA[3] in1[2]=comA[2] in1[1]=comA[1] 
+ in1[0]=shiftedToAdd[0] in2[23]=comB[23] in2[22]=comB[22] in2[21]=comB[21] 
+ in2[20]=comB[20] in2[19]=comB[19] in2[18]=comB[18] in2[17]=comB[17] 
+ in2[16]=comB[16] in2[15]=comB[15] in2[14]=comB[14] in2[13]=comB[13] 
+ in2[12]=comB[12] in2[11]=comB[11] in2[10]=comB[10] in2[9]=comB[9] 
+ in2[8]=comB[8] in2[7]=comB[7] in2[6]=comB[6] in2[5]=comB[5] in2[4]=comB[4] 
+ in2[3]=comB[3] in2[2]=comB[2] in2[1]=comB[1] in2[0]=outToAdd[0] 
XMux1 Multiplixer__parameterized0 $PINS Out[24]=outToShift[24] Out[23]=uc_5 
+ Out[22]=outToShift[22] Out[21]=outToShift[21] Out[20]=outToShift[20] 
+ Out[19]=outToShift[19] Out[18]=outToShift[18] Out[17]=outToShift[17] 
+ Out[16]=outToShift[16] Out[15]=outToShift[15] Out[14]=outToShift[14] 
+ Out[13]=outToShift[13] Out[12]=outToShift[12] Out[11]=outToShift[11] 
+ Out[10]=outToShift[10] Out[9]=outToShift[9] Out[8]=outToShift[8] 
+ Out[7]=outToShift[7] Out[6]=outToShift[6] Out[5]=outToShift[5] 
+ Out[4]=outToShift[4] Out[3]=outToShift[3] Out[2]=outToShift[2] 
+ Out[1]=outToShift[1] Out[0]=outToShift[0] A[24]=b[31] A[23]=uc_3 A[22]=b[22] 
+ A[21]=b[21] A[20]=b[20] A[19]=b[19] A[18]=b[18] A[17]=b[17] A[16]=b[16] 
+ A[15]=b[15] A[14]=b[14] A[13]=b[13] A[12]=b[12] A[11]=b[11] A[10]=b[10] 
+ A[9]=b[9] A[8]=b[8] A[7]=b[7] A[6]=b[6] A[5]=b[5] A[4]=b[4] A[3]=b[3] A[2]=b[2] 
+ A[1]=b[1] A[0]=b[0] B[24]=a[31] B[23]=uc_4 B[22]=a[22] B[21]=a[21] B[20]=a[20] 
+ B[19]=a[19] B[18]=a[18] B[17]=a[17] B[16]=a[16] B[15]=a[15] B[14]=a[14] 
+ B[13]=a[13] B[12]=a[12] B[11]=a[11] B[10]=a[10] B[9]=a[9] B[8]=a[8] B[7]=a[7] 
+ B[6]=a[6] B[5]=a[5] B[4]=a[4] B[3]=a[3] B[2]=a[2] B[1]=a[1] B[0]=a[0] 
+ Sel=borrow 
XMux2 Multiplixer__parameterized0__0_193 $PINS Out[24]=outToAdd[24] 
+ Out[23]=uc_2 Out[22]=outToAdd[22] Out[21]=outToAdd[21] Out[20]=outToAdd[20] 
+ Out[19]=outToAdd[19] Out[18]=outToAdd[18] Out[17]=outToAdd[17] 
+ Out[16]=outToAdd[16] Out[15]=outToAdd[15] Out[14]=outToAdd[14] 
+ Out[13]=outToAdd[13] Out[12]=outToAdd[12] Out[11]=outToAdd[11] 
+ Out[10]=outToAdd[10] Out[9]=outToAdd[9] Out[8]=outToAdd[8] Out[7]=outToAdd[7] 
+ Out[6]=outToAdd[6] Out[5]=outToAdd[5] Out[4]=outToAdd[4] Out[3]=outToAdd[3] 
+ Out[2]=outToAdd[2] Out[1]=outToAdd[1] Out[0]=outToAdd[0] A[24]=a[31] A[23]=uc_0 
+ A[22]=a[22] A[21]=a[21] A[20]=a[20] A[19]=a[19] A[18]=a[18] A[17]=a[17] 
+ A[16]=a[16] A[15]=a[15] A[14]=a[14] A[13]=a[13] A[12]=a[12] A[11]=a[11] 
+ A[10]=a[10] A[9]=a[9] A[8]=a[8] A[7]=a[7] A[6]=a[6] A[5]=a[5] A[4]=a[4] 
+ A[3]=a[3] A[2]=a[2] A[1]=a[1] A[0]=a[0] B[24]=b[31] B[23]=uc_1 B[22]=b[22] 
+ B[21]=b[21] B[20]=b[20] B[19]=b[19] B[18]=b[18] B[17]=b[17] B[16]=b[16] 
+ B[15]=b[15] B[14]=b[14] B[13]=b[13] B[12]=b[12] B[11]=b[11] B[10]=b[10] 
+ B[9]=b[9] B[8]=b[8] B[7]=b[7] B[6]=b[6] B[5]=b[5] B[4]=b[4] B[3]=b[3] B[2]=b[2] 
+ B[1]=b[1] B[0]=b[0] Sel=hfn_ipo_n3 
Xsub1 subtractor $PINS B2=borrow S2[7]=subsum[7] S2[6]=subsum[6] 
+ S2[5]=subsum[5] S2[4]=subsum[4] S2[3]=subsum[3] S2[2]=subsum[2] S2[1]=subsum[1] 
+ S2[0]=subsum[0] EA[7]=a[30] EA[6]=a[29] EA[5]=a[28] EA[4]=a[27] EA[3]=a[26] 
+ EA[2]=a[25] EA[1]=a[24] EA[0]=a[23] EB[7]=b[30] EB[6]=b[29] EB[5]=b[28] 
+ EB[4]=b[27] EB[3]=b[26] EB[2]=b[25] EB[1]=b[24] EB[0]=b[23] 
Xhfn_ipo_c3 CLKBUF_X2 $PINS Z=hfn_ipo_n3 A=borrow 
.ENDS
